(function(g){var window=this;'use strict';var E3=function(a){a.publish("cardstatechange",a.Rk()&&a.wp()?1:0)},F3=function(a,b){var c=g.cb(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},fpb=function(a){var b=g.Qs(a);
a=g.Ts(a);return new g.Es(b.x,b.y,a.width,a.height)},gpb=function(a,b,c){var d=void 0===d?{}:d;
var e;return e=g.GB(a,b,function(){g.HB(e);c.apply(a,arguments)},d)},I3=function(a){a=g.fb(a);
delete G3[a];g.gd(G3)&&H3&&H3.stop()},ipb=function(){H3||(H3=new g.wv(function(){hpb()},20));
var a=H3;a.isActive()||a.start()},hpb=function(){var a=g.kb();
g.Uc(G3,function(b){jpb(b,a)});
g.gd(G3)||ipb()},J3=function(a,b,c,d){g.Jv.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},jpb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;kpb(a,a.progress);1==a.progress?(a.j=0,I3(a),a.onFinish(),a.Vr()):a.isPlaying()&&a.DM()},kpb=function(a,b){"function"===typeof a.G&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},lpb=function(a,b){g.Ab.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},K3=function(a,b,c,d,e){J3.call(this,b,c,d,e);
this.element=a},mpb=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
K3.call(this,a,b,c,d,e)},npb=function(a){return Math.pow(a,3)},opb=function(a){return 3*a*a-2*a*a*a},ppb=function(a){g.I.call(this);
this.B=a||window;this.j=[]},L3=function(a){return a.baseUrl||null},M3=function(a,b){return g.Nt(g.Zr(a,b),function(c){return!!c})},qpb=function(a,b,c){function d(ka){var ia=ka.hovercardButton;
if(!ia)return null;ia=ia.subscribeButtonRenderer;if(!ia)return null;var sa=f(ia.unsubscribedButtonText),aa=f(ia.subscribedButtonText);if(ia.subscribed){var U=f(ia.subscriberCountWithUnsubscribeText);var Ja=f(ia.subscriberCountText)}else U=f(ia.subscriberCountText),Ja=f(ia.subscriberCountWithSubscribeText);var x=null;if(ka.signinEndpoint){x=F3(ka,"signinEndpoint","webNavigationEndpointData","url");if(!x){var ba,La;x=null==(La=g.V(null==(ba=ia.signInEndpoint)?void 0:ba.commandMetadata,g.x2))?void 0:
La.url}if(!x)return null}return sa&&(aa||x)?{subscribed:ia.subscribed,subscribeText:sa,subscribeCount:U,unsubscribeText:aa,unsubscribeCount:Ja,enabled:ia.enabled,signinUrl:x,classic:ka.useClassicSubscribeButton}:null}
function e(ka){if(ka){var ia=[],sa=ka.videoId;sa&&ia.push("v="+sa);(sa=ka.playlistId)&&ia.push("list="+sa);(ka=ka.startTimeSeconds)&&ia.push("t="+ka);return"/watch?"+ia.join("&")}}
function f(ka){if(!ka)return null;var ia=ka.simpleText;return ia?ia:ka.runs?g.Zr(ka.runs,function(sa){return sa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,v=null,w=!1,A=null,C=null,F=null,H=null,L=null,M=null;if("VIDEO"===h)g.V(l,g.qF)?m=g.V(l,g.qF).url:(M=g.V(l,g.OS),m=e(M)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.V(l,g.qF)?m=g.V(l,g.qF).url:(M=g.V(l,g.OS),m=e(M)),n=!1,q=a,t=f(b.playlistLength);else if("CHANNEL"===
h){if(w=F3(l,"browseEndpoint","browseId"))v=w,m="/channel/"+v;n=!1;q="new";(w=!!b.isSubscribe)?A=d(b):C=f(b.subscribersText)}else"WEBSITE"===h?((F=F3(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=F3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=F3(b,"title","accessibility","accessibilityData","label");var R=b.endpoint?b.endpoint.clickTrackingParams:null,
ea="";if(b.metadata){var ma=f(b.metadata);ma&&(ea=ma)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ea,callToAction:f(b.callToAction),pX:b.image,iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,dF:p,playlistLength:t,channelId:v,subscribeButton:A,subscribersText:C,isSubscribe:w,targetUrl:m||null,Q9:n,sessionData:R?{itct:R}:null,hea:q,CD:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:M3(b.impressionUrls||[],L3),F9:M3(b.hovercardShowUrls||[],L3),clickUrls:M3(l.loggingUrls||[],L3),visualElement:g.vE(b.trackingParams),productPrice:H,additionalFeesText:L,watchEndpoint:M||null}},rpb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:M3(a.impressionUrls||[],L3),elements:M3(a.elements||[],function(d,e){return qpb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.vE(a.trackingParams));return c},spb=function(a){g.tV.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.Y=!0;this.K=0;a=a.U();this.Z=g.FR(a)||g.HR(a);this.events=new g.XJ(this);g.N(this,this.events);this.events.T(this.player,g.cJ("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.dJ("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.jc);this.events.T(window,"focus",this.tca);this.load();var b=g.yf("STYLE");(g.nf("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.Hf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},tpb=function(a){return a.player.getVideoData().If?"current":a.Z?"new":"current"},N3=function(a){return"creator-endscreen-editor"===a.player.U().playerStyle},upb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=rpb(f,tpb(a))));O3(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.Pv;d&&(c.postParams={ad_tracking:d});if(b=g.XWa(b))if(b=g.je(b),b=g.de(b))a.C=g.VA(b,c)},O3=function(a,b,c){c=void 0===c?!0:c;
a.player.nf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.u(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};0<a.N.length&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&vpb(a);c=[];d=new g.bJ(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.W({I:"div",S:"ytp-ce-shadow"}),g.TT(a.player,a.B.element,4),a.D=new g.EF(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=wpb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.TT(a.player,f.element,4);var h=new g.bJ(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);xpb(a,f,e)}else g.BE(new g.XB("buildEndscreenElement null",
e))}a.player.gf(c);a.jc()}},vpb=function(a){var b=g.wE(),c=g.xE();
c&&b&&a.endscreen.visualElement&&g.BA(g.JE)(void 0,c,b,a.endscreen.visualElement)},wpb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ka:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.CD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:P3(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:Q3(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ka:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.Nv(b.title||"")},xa:b.title},{I:"div",S:b.dF?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
xa:b.videoDuration||void 0}]}]};c=new g.W(a);break;case "PLAYLIST":a={I:"div",Ka:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.CD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:P3(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:Q3(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ka:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.Nv(b.title||"")},xa:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",xa:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={I:"div",Ka:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.CD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",Ka:["ytp-ce-channel-title","ytp-ce-link"],X:{href:Q3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Nv(b.title||"")},xa:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",xa:b.subscribersText}:"",b.metadata?{I:"div",Ka:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],xa:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:P3(b)}]};c=new g.W(c);var d=g.of(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.Ev(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.cW(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",Ka:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.CD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",X:{dir:g.Nv(b.title||"")},xa:b.title},{I:"div",S:"ytp-ce-website-metadata",xa:b.metadata},{I:"a",Ka:["ytp-ce-website-goto","ytp-ce-link"],X:{href:Q3(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:P3(b)},{I:"div",S:"ytp-ce-expanding-icon",X:ypb(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",xa:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",xa:b.additionalFeesText})),a={I:"div",Ka:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.CD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",X:{dir:g.Nv(b.title||"")},xa:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",xa:b.metadata},{I:"a",Ka:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:Q3(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:P3(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
xa:b.callToAction||void 0}]}]},c=new g.W(a)}b.isPlaceholder&&g.Ev(c.element,"ytp-ce-placeholder");return c},P3=function(a){if(a.pX)var b=a.pX.thumbnails;
return ypb(b?b[b.length-1].url:null)},ypb=function(a){return a?{style:"background-image: url("+a+")"}:{}},xpb=function(a,b,c){function d(m){m&&(b.listen("blur",function(){"none"!=m.style.display&&a.Y&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;0<a.K?(g.Ev(b.element,"ytp-ce-force-expand"),R3(a,c.id,!0)):(g.Gv(b.element,"ytp-ce-force-expand"),g.Gv(b.element,"ytp-ce-element-hover"),R3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.listen("mouseenter",function(){zpb(a,b,c)});
b.listen("mouseleave",function(){Apb(a,b,c)});
a.player.U().B||b.listen("click",function(){g.Ev(b.element,"ytp-ce-element-hover")});
b.listen("click",function(m){Bpb(a,c,m)});
b.listen("keypress",function(m){Bpb(a,c,m)});
b.listen("focus",function(){zpb(a,b,c)});
b.listen("blur",function(){Apb(a,b,c)});
b.listen("touchstart",function(){zpb(a,b,c)});
var l=g.tf("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.Gv(b.element,"ytp-ce-element-hover");g.Gv(b.element,"ytp-ce-force-expand")});
b.listen("keydown",function(m){a.Y=9===m.keyCode&&!m.shiftKey});
d(g.tf("ytp-sb-subscribe",b.element));d(g.tf("ytp-sb-unsubscribe",b.element));b.listen("focus",f);b.listen("blur",h)},Bpb=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Dv(d,"ytp-ce-element");){g.Dv(d,"subscribe-label")&&Cpb(a,b);
if(g.Dv(d,"ytp-ce-channel-subscribe"))return;d=g.If(d)}if(!d||g.Dv(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Apb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.hea)Cpb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.je(Q3(a,b.targetUrl)),c=g.de(c),g.fG(c,void 0,b.sessionData);else{var e=g.QR(a.player.U())||a.player.getVideoData().If,f=function(){var h=Q3(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.GA(h);e&&n&&
(n.v||n.list)?a.player.Wo(n.v,l,n.list,!1,void 0,m||void 0):g.Kya(h,l)};
Cpb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},Q3=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.YR(a)+b}else return"";return b},zpb=function(a,b,c){g.Dv(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.Ev(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.wv(function(){g.Ev(b.element,"ytp-ce-element-hover")},200)).start():g.Ev(b.element,"ytp-ce-element-hover"),S3(a,c.F9),R3(a,c.id,!0))},Apb=function(a,b,c){g.Gv(b.element,"ytp-ce-element-hover");
g.Gv(b.element,"ytp-ce-force-expand");R3(a,c.id,!1)},R3=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.u(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.Iv(a.j[e].element,"ytp-ce-element-shadow-show",c)},S3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||N3(a))c&&c();else{b=Dpb(a,b);var e=0,f=!1,h=new g.wv(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.qD(b[a],d)}},Cpb=function(a,b,c){S3(a,b.clickUrls,c);
(a=g.xE())&&b.Q9&&g.QE(a,b.visualElement)},Dpb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Epb(b[d],c));return a},Epb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Fpb=function(a){return"string"===typeof a?a:""},T3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Gpb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},U3=function(a){return a.value?a.value:null},V3=function(a){if(!a)return null;
var b=g.je(Fpb(a.value));b=g.de(b);if(!b)return null;var c=T3(a.target,Hpb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Gpb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},Ipb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Lpb=function(a){if(!a)return null;
var b=T3(a.type,Jpb),c=T3(a.trigger,Kpb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=V3(a?a:null);return b?new Ipb(b,c,a):null},Mpb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},Npb=function(a,b){return g.Db(a.action,b)},Opb=function(a,b){this.context=a;
this.j=b},Ppb=function(a){return a.customMessage?W3("div","iv-card-message",a.customMessage):""},X3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",X:{style:a},V:c}},Qpb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.u(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(W3("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},W3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Nv(c);return{I:a,X:b,xa:c}},Rpb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.OD&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.OD+");");c.dir=g.Nv(a.customMessage);var d=[{I:"span",xa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",Ka:b,X:c,V:d}},Y3=function(a,b,c,d){if(d){b=g.u(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.gj.click,5)}},Spb=function(a,b){this.merchant=a;
this.price=b},Tpb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},Upb=function(a,b){return b?b:Tpb(a)?"current":"new"},Z3=function(a,b){g.I.call(this);
var c=this;this.element=a;this.context=b;this.rb=!1;this.Wa=new Map;this.eb=new Map;this.context.J.addEventListener(g.cJ("annotations_module"),function(d){(d=c.Wa.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.dJ("annotations_module"),function(d){(d=c.eb.get(d))&&d.apply(c)})},$3=function(a,b,c,d,e,f,h){a.context.j.listen(b,"click",function(l){a.EM(c,d,e,f||[],h||0,l)});
a.context.j.listen(b,"touchstart",function(){a.rb=!1});
a.context.j.listen(b,"touchmove",function(){a.rb=!0})},Vpb=function(a){var b;
return(null==(b=g.V(a,g.qF))?0:b.url)?g.V(a,g.qF).url:(a=g.V(a,g.OS))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},a4=function(a,b,c){return{OY:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
T1:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
ZL:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Wpb=function(a,b,c){Z3.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Hb=this.Na=this.Kb=this.C=this.isInitialized=!1;this.cards=[];this.zb=this.Z=this.La=this.G=this.Va=this.j=null;this.qa=[];this.ra=this.N=this.Ff=this.Ha=null;this.K=0;this.Fa=new g.wv(function(){},c.W.Kl?4E3:3E3);
g.N(this,this.Fa);this.gb=new g.wv(function(){});
g.N(this,this.gb);this.Ca=new Opb(c,function(e,f,h,l,m,n){$3(d,e,f,h,l,m,n)});
this.Y=new g.W({I:"div",S:"iv-drawer",X:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",X:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",Ka:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.N(this,this.Y);this.D=this.Y.element;this.bb=new g.EF(this.Y,330);g.N(this,this.bb);this.Jb=g.tf("iv-drawer-header-text",this.D);this.B=g.tf("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Kb&&b4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Kb=d.C)&&c4(d)});
this.Sa=new g.XJ(this);g.N(this,this.Sa);this.J.addEventListener("videodatachange",this.Ot.bind(this))},Xpb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){b4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){c4(a)});
var c=b.headerText;g.Kf(a.Jb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ha=g.vE(b.trackingParams);a.N=g.vE(b.closeTrackingParams);a.Ff=g.vE(b.iconTrackingParams)},Ypb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.fb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.dF(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,gj:{},zp:null,Kj:e.trackingParams?g.vE(e.trackingParams):null,Ff:f&&f.trackingParams?g.vE(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
OD:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};d4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.dF(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:e4(a,c,b,f),sponsored:!1,gj:a4(f,e,f.command),zp:f.trackingParams?g.vE(f.trackingParams):null,Kj:e.trackingParams?g.vE(e.trackingParams):null,Ff:l&&l.trackingParams?g.vE(l.trackingParams):null,imageUrl:f4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.dF(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,OD:null,title:f.title?g.dF(f.title):"",customMessage:f.callToAction?g.dF(f.callToAction):"",url:g.V(f.command,g.qF).url?V3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.V(f.command,g.qF).url}):null,onClickCommand:null};d4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.dF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:e4(a,c,b,e),sponsored:!1,gj:a4(e,f,e.endpoint),zp:e.trackingParams?g.vE(e.trackingParams):null,Kj:f.trackingParams?g.vE(f.trackingParams):null,Ff:l&&l.trackingParams?g.vE(l.trackingParams):null,channelId:g.V(e.endpoint,g.cT).browseId,customMessage:e.customText?g.dF(e.customText):null,profileImageUrl:f4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.dF(e.channelName):"",metaInfo:[e.subscriberCountText?g.dF(e.subscriberCountText):""],url:V3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.V(e.endpoint,g.cT).canonicalBaseUrl?g.V(e.endpoint,g.cT).canonicalBaseUrl:"/channel/"+g.V(e.endpoint,g.cT).browseId}),onClickCommand:null};d4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.dF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:e4(a,c,b,e),sponsored:!1,gj:a4(e,f,e.action),zp:e.trackingParams?g.vE(e.trackingParams):null,Kj:f.trackingParams?g.vE(f.trackingParams):null,Ff:l&&l.trackingParams?g.vE(l.trackingParams):null,lH:f4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.dF(e.customMessage):null,playlistVideoCount:g.dF(e.playlistVideoCount),title:e.playlistTitle?g.dF(e.playlistTitle):"",metaInfo:[e.channelName?g.dF(e.channelName):
"",e.videoCountText?g.dF(e.videoCountText):""],url:V3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Vpb(e.action)}),onClickCommand:null};d4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.dF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:e4(a,c,b,e),sponsored:!1,gj:a4(e,f,e.action),zp:e.trackingParams?g.vE(e.trackingParams):null,Kj:f.trackingParams?g.vE(f.trackingParams):null,Ff:l&&l.trackingParams?g.vE(l.trackingParams):null,lH:f4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.dF(e.lengthString):null,customMessage:e.customMessage?g.dF(e.customMessage):null,title:e.videoTitle?g.dF(e.videoTitle):"",metaInfo:[e.channelName?g.dF(e.channelName):
"",e.viewCountText?g.dF(e.viewCountText):""],isLiveNow:!!e.badge,url:V3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Vpb(e.action)}),onClickCommand:null};d4(a,b)}}}}}a.K++},f4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},e4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},$pb=function(a,b){if(b=Zpb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.Af.id),g.Hf(b.YN),g.Hb(a.cards,b),a.mI(),g4(a)},b4=function(a,b,c){if(!a.C){a.bb.show();
a.Va=new g.wv(function(){g.Ev(a.context.J.getRootNode(),g.IY.IV_DRAWER_OPEN)},0);
a.Va.start();a.Sa.T(a.B,"mousewheel",function(h){a.Fa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.xE();d&&a.Ha&&a.N&&g.OE(d,[a.Ha,a.N]);b={TRIGGER_TYPE:b};for(var e=g.u(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.JZ||(f.JZ=!0,aqb(a.context.logger,f.Af.gj.OY,b)),d&&g.OE(d,[f.Af.zp]);E3(a.J);c&&(a.G=new g.wv(function(){a.La=a.Z;a.zb.focus()},330),a.G.start())}},c4=function(a){a.C&&(a.bb.hide(),g.MB(a.Sa),g.Gv(a.context.J.getRootNode(),g.IY.IV_DRAWER_OPEN),a.C=!1,E3(a.J),a.G&&a.G.stop(),a.G=new g.wv(function(){a.La&&(a.La.focus(),a.La=null)},330),a.G.start())},bqb=function(a){g.Fv(a.Ib(),
[g.IY.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.TT(a.J,a.D,5);a.ED();a.Z=g.tf("ytp-cards-button",a.J.getRootNode());a.zb=g.tf("iv-drawer-close-button",a.D);a.isInitialized=!0},cqb=function(a){a.qa.push(g.ED("iv-teaser-shown",a.v4,a));
a.qa.push(g.ED("iv-teaser-hidden",a.k$,a));a.qa.push(g.ED("iv-teaser-clicked",a.u4,a));a.Hb=!0},dqb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.V(b.onClickCommand,g.Hlb))?void 0:c.targetId)?(a.ra=b,!0):!1},eqb=function(a,b){a.ra=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.uVa(c);if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.V(h[0],g.R2a))?void 0:d.timeRangeStartMillis)||0,a.ra=null,!0}return!1},d4=function(a,b){if(!dqb(a,b)||eqb(a,b)){var c=fqb(a,b);
if(c){var d={Af:b,YN:c.element,JZ:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Hb||cqb(a),$pb(a,b.id),c=a.findLastIndex(d),g.Ob(a.cards,c,0,d));else{a.isInitialized||bqb(a);$pb(a,b.id);var e=a.findLastIndex(d);g.Ob(a.cards,e,0,d);c.Ja(a.B,e);a.mI()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,g4(a),gqb(a,d),b4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&hqb(a,d),a.addCueRange(b.startMs,
b.startMs+1,b.id,function(){hqb(a,d)}),g4(a))}}},fqb=function(a,b){switch(b.type){case "simple":a=a.Ca;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",xa:b.displayDomain}:void 0;var d=Rpb(b);c={I:"div",Ka:["iv-card"],V:[{I:"a",S:"iv-click-target",X:{href:b.url?U3(b.url)||"":""},V:[X3(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[W3("h2",void 0,b.title),d]}]}]};c=new g.W(c);Y3(a,g.sf("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Ca;c={I:"div",Ka:["iv-card","iv-card-channel"],V:[{I:"a",Ka:["iv-click-target"],X:{href:U3(b.url)||"","data-ytid":b.channelId},V:[X3(b.profileImageUrl),
{I:"div",S:"iv-card-content",V:[Ppb(b),{I:"h2",S:"iv-card-primary-link",xa:b.title},Qpb(b)]}]}]};c=new g.W(c);Y3(a,g.sf("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Ca;c={I:"div",Ka:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",X:{href:U3(b.url)||""},V:[X3(b.lH,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",xa:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[Ppb(b),W3("h2","iv-card-primary-link",b.title),Qpb(b)]}]}]};
c=new g.W(c);Y3(a,g.sf("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Ca;var e=0!=b.offers.length;c=["iv-card"];d="";var f=Rpb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",xa:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",xa:f.merchant}),f={I:"div",V:e});e=b.url?U3(b.url)||"":"";c={I:"div",Ka:c,X:{tabindex:"0"},V:[{I:"a",Ka:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Sponsored",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",xa:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",X:{href:e},V:[W3("h2",d,b.title),f]}]}]};c=new g.W(c);d=g.yf("span");g.Kf(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Jd(d,"adInfo");Y3(a,g.sf("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Ca;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",xa:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ka:["yt-badge","yt-badge-live"],xa:"LIVE NOW"}:null;e={I:"div",Ka:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",X:{href:(null==(c=b.url)?void 0:U3(c))||""},V:[X3(b.lH,d),{I:"div",S:"iv-card-content",V:[Ppb(b),W3("h2","iv-card-primary-link",b.title),Qpb(b),f]}]}]};c=new g.W(e);Y3(a,g.sf("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},iqb=function(a){if(a.j)return"productListing"===a.j.Af.type;
if(a.J.L("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.$r(a.cards,function(c){return"productListing"===c.Af.type})}return g.$r(a.cards,function(c){return"productListing"===c.Af.type})},g4=function(a){g.Iv(a.J.getRootNode(),"ytp-cards-shopping-active",iqb(a))},hqb=function(a,b){if(!g.Dv(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.xE(),d=a.j?a.j.Af.Ff:a.Ff;
c&&d&&g.PE(c,[d]);a.j=b;g4(a)}(c=a.isInitialized&&"none"==a.Ib().style.display)||(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=!(1===c||3===c||d));c||b.Af.teaserDurationMs&&a.J.UB(!0,{teaserText:b.Af.teaserText,durationMs:b.Af.teaserDurationMs,onClickCommand:b.Af.onClickCommand});a.gb.isActive()||((!a.C||!a.Fa.isActive()&&a.Na)&&gqb(a,b),a.gb.start(910+b.Af.teaserDurationMs))}},gqb=function(a,b){a.Y.Gb?(b=new J3([0,
a.B.scrollTop],[0,b.YN.offsetTop],600,opb),a.context.C.listen(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.listen(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.$E(a.Y,!0),a.B.scrollTop=b.YN.offsetTop,g.$E(a.Y,!1))},h4=function(a){return a.j&&a.j.Af?a.j.Af:a.cards[0]&&a.cards[0].Af?a.cards[0].Af:null},Zpb=function(a,b){return g.Db(a.cards,function(c){return c.Af.id===b})},i4=function(a,b,c){Z3.call(this,a,b);
this.annotation=c;this.isActive=!1},jqb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},j4=function(a,b,c){i4.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},kqb=function(a,b){var c=void 0===c?0:c;
var d=fpb(b).width;g.Os(b,d);c=new mpb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,npb);g.N(a,c);a.context.C.listen(c,"begin",function(){g.Us(b,!0)});
c.play()},nqb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ka:["iv-branding-context-name"],xa:b.channel_name}),d=a.createElement({I:"div",Ka:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.cW(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Ja(d));var f=a.createElement({I:"div",Ka:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ka:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Us(h,!1);var l=a.createElement({I:"div",Ka:["branding-context-container-outer"]});l.appendChild(h);g.Hs(l,"right",b.image_width+"px");g.Bf(a.Ib(),l);a.C=new g.wv(function(){lqb(a,h,l)},500);
g.N(a,a.C);a.context.j.listen(a.Ib(),"mouseover",function(){mqb(a,h,l,f,b.image_height)});
a.context.j.listen(a.Ib(),"mouseout",function(){a.C.start()})}},mqb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.Ts(b);a.j||(b.style.width=g.Ns(f.width,!0),c.style.width=g.Ns(f.width,!0));g.Hs(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Hs(d,"right","1px");a.D=!0;g.Us(b,!0);a.G=new g.wv(function(){g.Ev(this.Ib(),"iv-branding-active")},0,a);
a.G.start()}},lqb=function(a,b,c){g.Gv(a.Ib(),"iv-branding-active");
a.K=new g.wv(function(){g.Us(b,!1);a.j||(c.style.width=g.Ns(0,!0))},250);
a.K.start();a.D=!1},oqb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.W=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},pqb=function(a,b,c){i4.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.Y=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",Ka:["iv-promo-contents"]});this.G=new g.wv(function(){d.j.setAttribute("aria-hidden","true");g.Us(d.C,!1);g.Us(d.B,!0)},700,this);
g.N(this,this.G)},sqb=function(a,b,c){c.stopPropagation();
qqb(a);rqb(a,b);a.j.focus()},tqb=function(a){a.isCollapsed||a.Z||a.D||(g.Ev(a.Ib(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},qqb=function(a){a.G.stop();
a.isCollapsed&&(g.Hv(a.Ib(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Us(a.B,!1),g.Us(a.C,!0))},rqb=function(a,b){a.D||(a.D=g.Ag(function(){uqb(this);
tqb(this)},b,a))},uqb=function(a){a.D&&(g.Ta.clearTimeout(a.D),a.D=null)},vqb=function(a){this.J=a},aqb=function(a,b,c){b&&(c?k4(a,b.map(function(d){return g.bv(d,c)})):k4(a,b))},k4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.u(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.qD(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},wqb=function(a){g.tV.call(this,a);
var b=this;this.qa=this.Z=!1;this.loadNumber=0;this.K={};this.logger=new vqb(this.player);this.D=new g.XJ(this);this.G=this.N=null;this.events=new g.XJ(this);this.Wg=this.Y=this.j=null;this.ra=[];g.N(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.publish("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.publish("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.publish("onShowControls")});
this.D.T(this.player,"resize",function(d){b.publish("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.publish("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.w4,this);this.subscribe("resize",this.RK,this);this.player.U().Na.subscribe("vast_info_card_add",this.T_,this);g.N(this,this.events);this.Ca=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.W({I:"div",Ka:["ytp-player-content","ytp-iv-player-content"]});g.N(this,this.B);g.TT(this.player,this.B.element,4);this.B.hide();this.C=new g.W({I:"div",Ka:["ytp-iv-video-content"]});g.N(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.Ca);this.C.element.appendChild(a);this.Qu()&&this.load();var c=this.createElement({I:"style"});(g.nf("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.Hf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},xqb=function(a){a=a.createElement({I:"div",
Ka:["annotation","annotation-type-custom"]});g.Us(a,!1);return a},yqb=function(a,b){b=!b.isCued()&&!g.LF(b,1024);
g.$E(a.B,b);g.$E(a.C,b)},zqb=function(a,b,c){a.Z=!0;
a.G=g.VA(b,c)},Aqb=function(a,b){for(var c={},d=g.u(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.db(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Aqb(a,e))}return c},Eqb=function(a){var b=a.player.getVideoData();
if(b.Va){var c=a.player.U().Na.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.OA(h)&&h.responseXML?h.responseXML:null)&&Bqb(a,h)}};
g.eC()&&(d.onFinish=Cqb(a,d.onFinish));d.postParams={ic_only:"1"};Dqb(d,c);a.Z=!0;g.VA(b.Va,d)}}},Dqb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.rI&&(a.postParams.ic_coll=b.rI);b.ZN&&(a.postParams.ic_xml=b.ZN);b.eM&&(a.postParams.ic_track=b.eM)},Fqb=function(a){var b=new g.W({I:"div"});
g.Us(b.element,!1);var c=new Wpb(a.player,b.element,l4(a));g.N(c,b);b.Ja(a.B.element);c.WG();return c},Hqb=function(a,b){var c,d;
if(b=null==(c=b.getWatchNextResponse())?void 0:null==(d=c.cards)?void 0:d.cardCollectionRenderer)a.qa=!0,Gqb(a,b),b.headerText&&a.Wg&&(c=g.dF(b.headerText),a.Wg.setAttribute("title",c))},l4=function(a){if(!a.Y){var b=new ppb(a);
g.N(a,b);var c=new g.wq(a);g.N(a,c);a.Y=new oqb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.vj)}return a.Y},Bqb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.xE();if(e){var f=g.wE();f&&g.BA(g.ixa)(void 0,e,f,[g.vE(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Aqb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=T3(f.type,Iqb),p=T3(f.style,Jqb),q=Fpb(f.data),r=0!==q.length?JSON.parse(q):{};var t=f.action;f=Lpb;if(null==t)var v=null;else if(g.cb(t)){l=[];for(var w=g.u(t),A=w.next();!A.done;A=w.next()){var C=f(A.value);
C&&l.push(C)}v=l}else{var F=f(t);v=F?[F]:[]}e=m&&n?new Mpb(m,n,p,v,r):null}else e=null}catch(ma){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var H=xqb(f),L=null;switch(l.type){case "branding":if(f.player.U().Rd)break;f.B.element.appendChild(H);L=new j4(H,l4(f),l);break;case "promotion":g.TT(f.player,H,4),L=new pqb(H,l4(f),l)}L&&L.WG();if(f=L)g.N(a,f),a.K[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=Fqb(a),g.N(a,a.j));if("card"===e.type){H=a.j;var M=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(M)switch(f=e.tracking||{},f={OY:f.impression,click:f.click,close:f.close,T1:f.teaser_impression,ZL:f.teaser_click},l=e.tracking_params||{},L=null,M){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,gj:f,zp:l.card?g.vE(l.card):null,Kj:l.teaser?g.vE(l.teaser):null,Ff:l.icon?g.vE(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:V3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};d4(H,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,gj:f,
zp:l.card?g.vE(l.card):null,Kj:l.teaser?g.vE(l.teaser):null,Ff:l.icon?g.vE(l.icon):null,lH:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:V3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};d4(H,c);break;case "productListing":e.signin_url&&(L=V3({target:"current",value:e.signin_url}));M=[];for(var R=e.offers||[],ea=0;ea<R.length;ea++)M.push(new Spb(g.bf(R[ea].merchant),
g.bf(R[ea].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,gj:f,zp:l.card?g.vE(l.card):null,Kj:l.teaser?g.vE(l.teaser):null,Ff:l.icon?g.vE(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,OD:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:V3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),orb:L,nrb:e.signin_title?e.signin_title:void 0,mrb:e.signin_message?e.signin_message:void 0,offers:M,onClickCommand:null};d4(H,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,gj:f,zp:l.card?g.vE(l.card):
null,Kj:l.teaser?g.vE(l.teaser):null,Ff:l.icon?g.vE(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,OD:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:V3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};d4(H,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,gj:f,zp:l.card?g.vE(l.card):null,Kj:l.teaser?g.vE(l.teaser):null,Ff:l.icon?g.vE(l.icon):null,lH:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:V3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},d4(H,c)}}else Xpb(a.j,e);c=!0}}c&&
(E3(a.player),a.RK())},Gqb=function(a,b){var c=!1;
a.j||(a.j=Fqb(a),g.N(a,a.j));for(var d=g.u(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(Ypb(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.jT(f)||(c=a.j,d=b.headerText?g.dF(b.headerText):"",g.Kf(c.Jb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ha=b.trackingParams?g.vE(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.vE(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Ff=b.icon.infoCardIconRenderer.trackingParams?g.vE(b.icon.infoCardIconRenderer.trackingParams):null,a.RK());E3(a.player)}},Kqb=function(a,b,c,d,e){if(!a.player.U().Rd){var f=[];
b.navigationEndpoint&&g.V(b.navigationEndpoint,g.cT)&&g.V(b.navigationEndpoint,g.cT).browseId&&f.push(new Ipb("openUrl","click",new Gpb("/channel/"+g.V(b.navigationEndpoint,g.cT).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.V(b.subscribeButton,
g.dT)){d.channel_id=g.V(b.subscribeButton,g.dT).channelId;var l;b=g.V(b.subscribeButton,g.dT);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.dF(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.dF(b.subscriberCountText))):(b.subscriberCountText&&(e=g.dF(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.dF(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.V(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.x2))?void 0:m.url)||"";l={subscribeText:g.dF(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.dF(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new Mpb(c,"branding","branding",f,d);l=xqb(a);a.B.element.appendChild(l);f=new j4(l,l4(a),f);f.WG();g.N(f,f);a.K[c]=f}},Cqb=function(a,b){return function(){var c=g.Ia.apply(0,arguments);
a.Ma()||a.ra.push(g.ev.Pi(function(){b.apply(null,g.qa(c))}))}},Lqb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.MT.prototype.UB=g.fa(28,function(a,b){var c=g.LV(this.yb());c&&c.UB(a,b)});
var G3={},H3=null;g.nb(J3,g.Jv);g.k=J3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;I3(this);this.startTime=a=g.kb();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.IK();this.Dn("play");this.isPaused()&&this.Dn("resume");this.j=1;var b=g.fb(this);b in G3||(G3[b]=this);ipb();jpb(this,a);return!0};
g.k.stop=function(a){I3(this);this.j=0;a&&(this.progress=1);kpb(this,this.progress);this.onStop();this.Vr()};
g.k.pause=function(){this.isPlaying()&&(I3(this),this.j=-1,this.Dn("pause"))};
g.k.va=function(){0==this.j||this.stop(!1);this.Dn("destroy");J3.Of.va.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.DM=function(){this.Dn("animate")};
g.k.Dn=function(a){this.dispatchEvent(new lpb(a,this))};
g.nb(lpb,g.Ab);g.nb(K3,J3);K3.prototype.C=function(){};
K3.prototype.DM=function(){this.C();K3.Of.DM.call(this)};
K3.prototype.Vr=function(){this.C();K3.Of.Vr.call(this)};
K3.prototype.IK=function(){this.C();K3.Of.IK.call(this)};
g.nb(mpb,K3);mpb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.y(ppb,g.I);g.k=ppb.prototype;g.k.listen=function(a,b,c,d){c=(0,g.gb)(c,d||this.B);a=g.GB(a,b,c);this.j.push(a);return a};
g.k.vF=function(a,b,c,d){c=(0,g.gb)(c,d||this.B);a=gpb(a,b,c);this.j.push(a);return a};
g.k.Pc=function(a){g.HB(a);g.Hb(this.j,a)};
g.k.removeAll=function(){g.HB(this.j);this.j.length=0};
g.k.va=function(){this.removeAll();g.I.prototype.va.call(this)};g.y(spb,g.tV);g.k=spb.prototype;g.k.load=function(){g.tV.prototype.load.call(this);if(!N3(this)){var a=g.YWa(this.player.getVideoData());a?(a=rpb(a,tpb(this)),O3(this,a,!1)):upb(this)}};
g.k.unload=function(){O3(this,null);this.C&&(this.C.abort(),this.C=null);g.tV.prototype.unload.call(this)};
g.k.Qh=function(a,b){return N3(this)?"loadCustomEndscreenRenderer"===a?(a=rpb(b,"new"),O3(this,a),!0):null:null};
g.k.getOptions=function(){return N3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.jc=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Mqb.length;f++){var h=Math.abs(b.width-Mqb[f]);if(-1===e||d>=h)e=f,d=h}d=Nqb[e];this.B&&g.Hs(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Ss(e.element,m,f);g.Os(e.element,n,p);g.Hv(e.element,Oqb);256<m||256<f?g.Ev(e.element,"ytp-ce-large-round"):96<m||96<f?g.Ev(e.element,"ytp-ce-medium-round"):g.Ev(e.element,"ytp-ce-small-round");g.Hv(e.element,Pqb);m=h.left+h.width/2;h=h.top+l/2;g.Ev(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Hv(e.element,Nqb);g.Ev(e.element,d);(e=g.of(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Hs(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())S3(this,this.endscreen.impressionUrls),(a=g.xE())&&this.endscreen.visualElement&&g.NE(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.Ev(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.Ev(b,"ytp-ce-shown");S3(this,c.impressionUrls);(b=g.xE())&&g.NE(b,c.visualElement);this.player.U().N&&this.player.jb("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.Gv(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Gv(b,"ytp-ce-shown");this.player.U().N&&this.player.jb("endscreenelementhidden",a)}};
g.k.tca=function(a){var b=this;a.target===window&&(new g.wv(function(){for(var c=g.u(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.Hv(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var Mqb=[346,426,470,506,570,640,853,1280,1920],Nqb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Pqb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Oqb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Hpb={kwa:"current",wXa:"new"};var Jpb={CLOSE:"close",n0a:"openUrl",SUBSCRIBE:"subscribe"},Kpb={vua:"click",CLOSE:"close",oIa:"hidden",u6a:"rollOut",v6a:"rollOver",m8a:"shown"};Mpb.prototype.Je=function(){var a=Npb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var Jqb={Joa:"anchored",v3:"branding",CHANNEL:"channel",Zva:"cta",rIa:"highlightText",vMa:"label",PLAYLIST:"playlist",POPUP:"popup",sab:"speech",SUBSCRIBE:"subscribe",ieb:"title",VIDEO:"video",Mlb:"website"},Iqb={v3:"branding",Vra:"card",iya:"drawer",qIa:"highlight",NSa:"marker",E4a:"promotion",TEXT:"text",unb:"widget"};g.y(Z3,g.I);g.k=Z3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.bJ(a,b,{id:c,namespace:"annotations_module"});d&&this.Wa.set(a,d);e&&this.eb.set(a,e);this.context.J.gf([a])};
g.k.WG=function(){this.context.B.subscribe("resize",this.mI,this)};
g.k.Ib=function(){return this.element};
g.k.EM=function(a,b,c,d,e,f){if(this.rb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Hf(this.Ib())};
g.k.mI=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=U3(a);if(f){var h=Upb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.If||!1,n=g.GA(f||"");m&&n&&(n.v||n.list)?e.context.J.Wo(n.v,b,n.list,!1):g.fG(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);k4(this.context.logger,c,l,d);Tpb(f)||(c=g.xE(),d=b.itct,c&&d&&g.QE(c,g.vE(d)))}};
g.k.va=function(){this.Wa.clear();this.eb.clear();g.I.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.N(this,a);return a.element};g.y(Wpb,Z3);g.k=Wpb.prototype;g.k.Ot=function(){this.ra&&d4(this,this.ra)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.Ts(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.mI=function(){var a=this.isAvailable();g.Us(this.Ib(),a);g.Iv(this.context.J.getRootNode(),g.IY.IV_DRAWER_ENABLED,a);E3(this.J)};
g.k.destroy=function(){this.J.UB(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.FD(this.qa);g.MB(this.Sa);this.Va&&this.Va.dispose();this.G&&this.G.dispose();Z3.prototype.destroy.call(this)};
g.k.ED=function(){var a=this,b=g.tf("iv-drawer-close-button",this.D);this.context.j.listen(b,"click",this.q7,this);this.context.j.listen(this.B,"touchend",function(){a.Fa.start()});
this.context.j.listen(this.B,"scroll",this.M7,this);this.context.B.subscribe("onHideControls",function(){a.Na=!0});
this.context.B.subscribe("onShowControls",function(){a.Na=!1});
this.context.B.subscribe("onVideoAreaChange",function(){a.Na=g.Dv(a.J.getRootNode(),"ytp-autohide")});
this.qa.push(g.ED("iv-button-shown",this.j$,this));this.qa.push(g.ED("iv-button-hidden",this.i$,this));cqb(this)};
g.k.findLastIndex=function(a){if(0===this.cards.length)return 0;var b=g.Eb(this.cards,function(c){return a.Af.startMs>c.Af.startMs||a.Af.startMs===c.Af.startMs&&a.Af.timestamp>=c.Af.timestamp?!0:!1});
return-1===b?0:b+1};
g.k.q7=function(){if(this.C){k4(this.context.logger,h4(this).gj.close);var a=g.xE();a&&this.N&&g.QE(a,this.N);c4(this)}};
g.k.M7=function(){g.Iv(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.j$=function(){var a=g.xE(),b=h4(this);b=b?b.Ff:this.Ff;a&&b&&g.OE(a,[b])};
g.k.i$=function(){var a=g.xE(),b=h4(this);b=b?b.Ff:this.Ff;a&&b&&g.PE(a,[b])};
g.k.v4=function(){var a=h4(this);k4(this.context.logger,a.gj.T1);var b=g.xE();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.Kj&&c.push(a.Kj);a.Ff&&c.push(a.Ff);0<c.length&&g.OE(b,c)}else g.OE(b,[a.Kj,a.Ff])};
g.k.k$=function(){var a=g.xE(),b=h4(this);a&&b&&g.PE(a,[b.Kj])};
g.k.u4=function(a){var b=h4(this),c=g.xE();this.j?a?(a=this.context.logger,k4(a,b.gj.ZL),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Kj&&g.QE(c,b.Kj)):(a=this.context.logger,k4(a,b.gj.ZL),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Ff&&g.QE(c,b.Ff)):(a=this.context.logger,k4(a,b.gj.ZL),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Ff&&g.QE(c,this.Ff))};g.y(i4,Z3);i4.prototype.WG=function(){Z3.prototype.WG.call(this);jqb(this)};
i4.prototype.show=function(){Z3.prototype.show.call(this);var a=g.xE(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.OE(a,[g.vE(b.itct)])};
i4.prototype.hide=function(){Z3.prototype.hide.call(this);var a=g.xE(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.PE(a,[g.vE(b.itct)])};g.y(j4,i4);
j4.prototype.Zx=function(){g.Ev(this.Ib(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Ka:["branding-img","iv-click-target"],X:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Us(this.B,!1);var b=this.createElement({I:"button",Ka:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Ib().appendChild(b);var c=this.annotation.Je();c&&$3(this,b,c,this.annotation.id,a.session_data);this.context.J.L("disable_branding_context")||nqb(this,
a)};
j4.prototype.show=function(){if(!this.isActive&&(i4.prototype.show.call(this),this.N||(this.Zx(),this.N=!0),g.Us(this.Ib(),!0),this.isActive=!0,this.B)){try{kqb(this,this.B)}catch(a){}g.Ev(this.context.J.getRootNode(),"ytp-branding-shown")}};
j4.prototype.hide=function(){this.isActive&&(i4.prototype.hide.call(this),g.Us(this.Ib(),!1),this.isActive=!1,g.Gv(this.context.J.getRootNode(),"ytp-branding-shown"))};
j4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);i4.prototype.destroy.call(this)};g.y(pqb,i4);g.k=pqb.prototype;
g.k.Zx=function(){var a=this,b=this.annotation.data;if("cta"===this.annotation.style)var c=6;else if("video"===this.annotation.style||"playlist"===this.annotation.style)c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Ib().setAttribute("aria-hidden","true");this.Ib().setAttribute("aria-label","Promotion");this.Ib().tabIndex=0;var e=this.annotation.Je(),f=b.image_url;if(f){var h=this.createElement({I:"div",Ka:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",xa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",xa:b.playlist_length.toString()}),h.appendChild(f));e&&$3(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Me(f,U3(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",xa:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",xa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Ka:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Ka:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",xa:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&$3(this,
this.Ib(),e,this.annotation.id,b.session_data,void 0,c)}g.Ev(this.j,"iv-click-target");e&&$3(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",xa:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",xa:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Ka:["yt-badge","iv-promo-badge-live"],xa:"LIVE NOW"})),g.Ev(this.j,"iv-click-target"),e&&$3(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",Ka:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.listen(this.B,"click",function(q){sqb(a,5E3,q)});
c.appendChild(this.B);g.Us(this.B,!1);this.context.j.listen(this.Ib(),"mouseover",this.g9,this);this.context.j.listen(this.Ib(),"mouseout",this.f9,this);this.context.j.listen(this.Ib(),"touchend",function(q){sqb(a,5E3,q)});
this.C=this.createElement({I:"button",Ka:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.listen(this.C,"click","cta"===this.annotation.style&&b.text_line_3?this.b9:this.a9,this);c.appendChild(this.C);g.Fv(this.Ib(),d);h&&(g.Bf(this.Ib(),h),n&&h.appendChild(n));g.Bf(this.Ib(),this.N);g.Bf(this.Ib(),c)};
g.k.show=function(){this.isActive||(i4.prototype.show.call(this),this.Y||(this.Zx(),this.Y=!0),g.Us(this.Ib(),!0),g.Ag(function(){g.Gv(this.Ib(),"iv-promo-inactive")},100,this),this.Ib().removeAttribute("aria-hidden"),this.isActive=!0,uqb(this),qqb(this),rqb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.Ev(this.Ib(),"iv-promo-inactive"),this.isActive=!1,this.Ib().setAttribute("aria-hidden","true"))};
g.k.EM=function(a,b,c,d,e,f){return this.isCollapsed?!1:i4.prototype.EM.call(this,a,b,c,d,e,f)};
g.k.g9=function(a){this.Z=!0;sqb(this,500,a)};
g.k.f9=function(){this.Z=!1;tqb(this)};
g.k.a9=function(a){a.stopPropagation();this.hide()};
g.k.b9=function(a){a.stopPropagation();uqb(this);this.isCollapsed=!0;g.Ev(this.Ib(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();i4.prototype.destroy.call(this)};g.y(wqb,g.tV);g.k=wqb.prototype;g.k.Qh=function(a,b){if(!Lqb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.c2(b))&&Bqb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&($pb(this.j,b),E3(this.player)),!0}return null};
g.k.getOptions=function(){return Lqb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Qu=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.uT(b)||g.FT(this.player.app)?!1:1===c&&!b.sX||a.Na.get(b.videoId)||g.kT(b)||g.ZWa(b)?!0:!1};
g.k.RK=function(){if(this.C){var a=this.player.ob().getVideoContentRect(!0);g.Ss(this.C.element,a.width,a.height);g.Os(this.C.element,a.left,a.top)}if(this.j){var b=this.player.Nn();a=this.j;b=b.width;g.Iv(a.D,"iv-drawer-small",426>=b);g.Iv(a.D,"iv-drawer-big",1280<=b)}};
g.k.w4=function(a){yqb(this,a.state);g.LF(a.state,2)&&(this.Rk()&&this.wp()&&2!==this.player.getPresentingPlayerType()&&this.VB(!1),this.UB(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.OA(h)&&h.responseXML?h.responseXML:null)&&(Bqb(b,h),g.Ev(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.tV.prototype.load.call(this);yqb(this,this.player.getPlayerStateObject());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.eC()&&(a=Cqb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Na.get(d);f&&Dqb(e,f);f=f&&(f.ZN||f.rI);if(!c.yv||f)c.Va?zqb(this,c.Va,e):(this.N=function(){if(!b.Z)b.onVideoDataChange(e);var h=b.player.getVideoData();(null==h?0:g.jT(h))&&!b.qa&&Hqb(b,h)},this.player.addEventListener("videodatachange",this.N));
g.TT(this.player,this.C.element,4);this.RK();(f=g.kT(c))&&Gqb(this,f);(f=g.ZWa(c))&&f.featuredChannel&&Kqb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.Wg=g.tf("ytp-cards-button",this.player.getRootNode());g.jT(c)&&Hqb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Va&&zqb(this,b.Va,a)};
g.k.unload=function(){this.player.nf("annotations_module");for(var a=g.u(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.Y=null;this.j&&(this.j.destroy(),this.j=null,E3(this.player));this.Z=!1;this.G&&(this.G.abort(),this.G=null);this.qa=!1;this.K={};this.B.hide();g.tV.prototype.unload.call(this);this.C.detach();this.N&&(this.player.removeEventListener("videodatachange",this.N),this.N=null)};
g.k.T_=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Eqb(this):this.load())};
g.k.Rk=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.qa};
g.k.wp=function(){return!!this.j&&this.j.C};
g.k.VB=function(a,b,c){b=void 0===b?!1:b;this.Rk();this.j&&(a?c?b4(this.j,c,b):b4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):c4(this.j))};
g.k.UB=function(a,b){this.player.publish(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.va=function(){this.player.U().Na.unsubscribe("vast_info_card_add",this.T_,this);g.Gv(this.player.getRootNode(),g.IY.IV_DRAWER_OPEN);for(var a=this.ra,b=g.ev,c=0,d=a.length;c<d;c++)b.Qj(a[c]);this.ra.length=0;g.tV.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.N(this,a);return a.element};g.sV("annotations_module",wqb);g.sV("creatorendscreen",spb);})(_yt_player);
