(function(g){var window=this;'use strict';var m4=function(a){a.isActive()||a.start()},Sqb=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},Tqb=function(a,b){var c=new g.eS;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.displayName=a.displayName;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;a.xtags&&(c.xtags=a.xtags);a.captionId&&(c.captionId=a.captionId);return c},Uqb=function(a,b){var c,d,e;
return g.G(function(f){if(1==f.j)return c=a+"|"+b,g.z(f,g.PC(),2);if(3!=f.j){d=f.B;if(!d)throw g.sC("gct");return g.z(f,g.tS(d),3)}e=f.B;return f.return(e.get("captions",c))})},Vqb=function(a,b,c){Uqb(a,b).then(function(d){d&&c(d.trackData,new g.eS(d.metadata))})},Yqb=function(a){if(!Wqb.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Xqb,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},Zqb=function(){return g.QB("yt-player-caption-display-settings")},n4=function(){this.segments=[]},$qb=function(a,b){var c=g.Sb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.Gb(a.segments,c),g.Gb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.Ob(a.segments,c,0,b),g.Ob(a.segments,c+1,0,b)))},arb=function(a,b,c,d,e,f){g.I.call(this);
this.policy=a;this.player=b;this.qa=c;this.Z=d;this.G=e;this.Y=f;this.D=new n4;this.K=-1;this.C=this.B=this.j=null;this.N=new g.wv(this.AZ,1E3,this);this.events=new g.XJ(this);g.N(this,this.N);g.N(this,this.events);this.events.T(b,"SEEK_COMPLETE",this.oB);this.oB();this.AZ()},brb=function(a){return a.j&&a.j.D?a.j.D+a.player.Lc()<a.player.getCurrentTime():!1},crb=function(a,b){var c=g.aSa(b,a.policy,{}).Je(),d={format:"RAW",
withCredentials:!0};if(a.policy.Ha){d.method="POST";var e=b.D,f=(0,g.jZ)([120,0]);e&&g.lO(e,g.QPa);d.postBody=f}a.G&&(d.responseType="arraybuffer");a.C=g.YA(c,d,3,100).then(function(h){a:{h=h.xhr;a.Ma();if(a.B){var l=!(a.G?h.response:h.responseText)||400<=h.status,m=g.ISa(h);if(m){h=g.aSa(a.B,a.policy,{});a.B.Zk(h,m);crb(a,a.B);break a}l?a.player.ma("capfail",{status:h.status}):(a.player.Ci().Ji("fcb_r"),m=a.B.ib[0].Pa,null!=a.Z&&a.K!==m&&(l=a.B.ib[0],a.G?a.Z(h.response,1E3*(l.startTime+a.player.Lc())):
a.Z(h.responseText,1E3*(l.startTime+a.player.Lc())),a.K=m))}a.B=null;a.C=null}}).Cl(function(h){a.B=null;
a.C=null;var l;a.player.ma("capfail",{status:null==(l=h.xhr)?void 0:l.status})});
a.B=b;$qb(a.D,a.B.ib[0].Pa)},o4=function(a,b){g.wV.call(this,b.U());
this.j=a;this.J=b;this.C=null;this.G=!1;this.K=g.FI(this.J.U())&&!this.j.isManifestless},erb=function(a,b){var c=[],d;
for(d in a.j.j)if(a.j.j.hasOwnProperty(d)){var e=a.j.j[d];if(g.m_a(e,b||null)){var f=e.info.id,h=f,l="."+f,m="",n="",p="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind,a.J.U().L("html5_expose_xtags_through_caption_track")&&(n=e.xtags),p=e.id;else{e=f;var q=g.Sob.get(e);null==q&&(q=drb[e]||drb[e.replace(/-/g,"_")],g.Sob.set(e,q));h=q||h}c.push(new g.eS({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m,xtags:n,captionId:p}))}}return c},
frb=function(a,b){return null!=b&&b in a.j.j?a.j.j[b]:null},grb=function(a,b,c){var d=[],e;
for(e in a.j.j)if(a.j.j.hasOwnProperty(e)){var f=a.j.j[e];if(g.m_a(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},hrb=function(){var a=void 0;
a=void 0===a?{}:a;var b="suggest_correction"in g.epb?g.epb.suggest_correction:"Edit caption";b=b||"";var c={},d;for(d in a){c={mF:c.mF};c.mF=d;var e=function(f){return function(){return String(a[f.mF])}}(c);
b=b.replace(new RegExp("\\$\\{"+c.mF+"\\}","gi"),e);b=b.replace(new RegExp("\\$"+c.mF,"gi"),e)}return b},p4=function(a,b,c,d,e,f,h,l,m,n){var p=n.isInline()&&!0,q={};
Object.assign(q,b);Object.assign(q,a.params);Object.assign(q,c);var r={};Object.assign(r,b.Pe);a.params.Pe&&Object.assign(r,a.params.Pe);Object.assign(r,c.Pe);p&&(q.windowOpacity=.6,r.backgroundOpacity=0);q.Pe=r;var t=1===q.Ii,v=[{I:"span",S:"captions-text",X:{style:"word-wrap: normal; display: block;"}}],w,A,C;(l=l.fb("caption_edit_on_hover")&&(null==(w=n.getVideoData().getPlayerResponse())?void 0:null==(A=w.captions)?void 0:null==(C=A.playerCaptionsTracklistRenderer)?void 0:C.openTranscriptCommand))&&
v.unshift({I:"button",S:"caption-edit",X:{tabindex:"0","aria-label":hrb()},V:[{I:"svg",X:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},V:[{I:"path",X:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.W.call(this,{I:"div",S:"caption-window",X:{id:"caption-window-"+a.id,dir:t?"rtl":"ltr",tabindex:"0",lang:q.lang},V:v});var F=
this;this.K=[];this.Ha=!1;this.B=a;this.Na=this.La=null;this.playerWidth=f;this.playerHeight=h;this.N=null;this.maxWidth=.96*f;this.maxHeight=.96*h;this.j=q;this.Dc=c;this.ra=b;this.D=this.Ga("captions-text");this.Nb=""!==this.D.style.getPropertyValue("box-decoration-break")||""!==this.D.style.getPropertyValue("-webkit-box-decoration-break");this.Va=irb(d,e,f,h);this.vc=m;l&&(this.G=this.Ga("caption-edit"),this.T(this.G,"click",function(){F.vc()}));
this.type=0;this.eb=this.Va*jrb(r);this.Hb=p;a=new g.TU(this.element,!0);g.N(this,a);a.subscribe("dragstart",this.z4,this);a.subscribe("dragmove",this.y4,this);a.subscribe("dragend",this.x4,this);this.gb=this.bb=this.zb=this.rb=0;a="";this.j.windowOpacity&&(a=Yqb(this.j.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");b={"background-color":a,display:!1===this.j.isVisible?"none":"","text-align":krb[this.j.textAlign]};this.Nb&&(b["border-radius"]=a?this.eb/8+"px":"");(this.C=
2===this.B.params.Ii||3===this.B.params.Ii)&&lrb(this,this.element);g.Hs(this.element,b);if(p){var H;null==(H=this.element.parentElement)||H.style.setProperty("--caption-window-color",a)}switch(this.j.gm){case 0:case 1:case 2:g.Ev(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Ev(this.element,"ytp-caption-window-bottom")}},lrb=function(a,b){var c="vertical-rl";
1===a.j.rT&&(c="vertical-lr");g.Js&&(c="vertical-lr"===c?"tb-lr":"tb-rl");g.Hs(b,"-o-writing-mode",c);g.Hs(b,"-webkit-writing-mode",c);g.Hs(b,"writing-mode",c);g.Hs(b,"text-orientation","upright");g.Ev(b,"ytp-vertical-caption");3===a.B.params.Ii&&(g.Hs(b,"text-orientation",""),g.Hs(b,"transform","rotate(180deg)"))},jrb=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},mrb=function(a,b){var c={},d=b.background?b.background:a.j.Pe.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.j.Pe.backgroundOpacity;d=Yqb(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Nb&&(c["box-decoration-break"]="clone",c["border-radius"]=a.eb/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Va*jrb(b)+"px";d=1;e=b.color||a.j.Pe.color;if(b.color||null!=b.textOpacity)e=Yqb(e),d=null==b.textOpacity?a.j.Pe.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.aO&&(h=e=b.aO);var l=a.Va/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.hB()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.j.Pe.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]=
"italic");b.underline&&(c["text-decoration"]="underline");b.C9&&(c.visibility="hidden");1===b.LY&&a.C&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.TR||g.rC,3===a.B.params.Ii?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.No||2===b.No||3===b.No||4===b.No||5===b.No)if(g.TR)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.No){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},q4=function(a){a=a.split("px");
return 0<a.length?(a=Number(a[0]))?a:0:0},nrb=function(a){a.N=g.yf("SPAN");
g.Hs(a.N,{display:"block"});g.Ev(a.N,"caption-visual-line");a.D.appendChild(a.N)},orb=function(a,b){var c=g.yf("SPAN");
g.Hs(c,{display:"inline-block","white-space":"pre-wrap"});g.Hs(c,mrb(a,b));c.classList.add("ytp-caption-segment");a.N.appendChild(c);c.previousElementSibling&&(g.Hs(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Hs(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},prb=function(a,b,c){a.Ha=a.Ha||!!c;
var d={};Object.assign(d,a.j.Pe);Object.assign(d,c||b.j);Object.assign(d,a.Dc.Pe);(c=!a.N)&&nrb(a);for(var e=a.La&&a.Na&&g.id(d,a.Na)?a.La:orb(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(nrb(a),e=orb(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.zf(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.TR||!g.Ks(n.children[2],"text-emphasis")||(m=a.C?"padding-right":"padding-top",g.Ks(n.children[2],"text-emphasis-position")&&(m=
a.C?"padding-left":"padding-bottom"),g.Pc?g.Hs(e,m,"1em"):g.Hs(e,m,"0.5em")))}a.Na=d;a.La=e;a.K.push(b)},irb=function(a,b,c,d){var e=b/360*16;
b>=a&&(a=640,d>1.3*c&&(a=480),e=c/a*16);return e},rrb=function(){this.C=this.time=this.mode=this.B=0;
this.D=new qrb(this);this.G=new qrb(this);this.j=[];this.clear()},trb=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Xv:a,
Ws:b,result:0};a=srb[a];b=srb[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.qe()&&c.Ws===d;if(d)return{Xv:a,Ws:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Xv:a,Ws:b,result:2};return{Xv:a,Ws:b,result:3}},vrb=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.C&&a.reset(),a.D.B.clear(),a.G.B.clear()):(a.C=0,urb(a.D,b,c,d))},wrb=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.u(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?vrb(a,d.MW,d.NW,b):1===d.type&&a.B&496&&urb(a.G,d.MW,d.NW,b);a.j.length=0},r4=function(){this.type=0},s4=function(){this.state=this.Ws=this.Xv=0},xrb=function(){this.timestamp=this.j=0},t4=function(a){this.D=a;
this.B=[];this.j=this.col=this.row=0;this.style=new r4;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new xrb}},u4=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.j){0===c&&(c=m,d=p);n=String.fromCharCode(q.j);var r=q.timestamp;r<e&&(e=r);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===q.j||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],q=p.j,0!==q&&(0===c&&(c=h,d=m),n=String.fromCharCode(q),r=p.timestamp,r<=e&&(e=r),l+=n,p.reset()),32===m||0===q)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},Crb=function(a,b){switch(a){case 0:return yrb[(b&127)-32];
case 1:return zrb[b&15];case 2:return Arb[b&31];case 3:return Brb[b&31]}return 0},v4=function(a){return a.B[a.row][a.col]},w4=function(a,b,c){2<=b&&1<a.col&&(--a.col,v4(a).j=0);
var d=v4(a);d.timestamp=a.D.time+0;d.j=Crb(b,c);32>a.col&&a.col++},Drb=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},x4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},Erb=function(a){a.row=0<a.j?a.j:1;
a.col=1;x4(a,0,15)},Frb=function(a){this.C=a;
this.G=0;this.style=new r4;this.K=new t4(this.C);this.N=new t4(this.C);this.text=new t4(this.C);this.B=this.K;this.D=this.N;this.j=this.B},Grb=function(a,b,c){var d=a.B,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.j||(u4(d,c),Erb(a.B),Erb(a.D),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.C.mode=1<<d.C;e?d.col=1:d.j!==b&&(d.j>b?(u4(d,c),x4(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},Hrb=function(a){a.style.set(1);
a.j=a.D;a.j.j=0;a.j.style=a.style;a.C.mode=1<<a.j.C},Irb=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.C.mode=1<<a.j.C},qrb=function(a){this.j=a;
this.G=0;this.C=new Frb(this.j);this.K=new Frb(this.j);this.B=new s4;this.D=this.C},urb=function(a,b,c,d){a.B.update();
b=trb(b,c,a.B);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Xv;c=b.Ws;if(32<=e||!e)a.j.mode&a.j.B&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.D.j,b&96&&w4(a,0,b),c&96&&w4(a,0,c),0!==b&&0!==c&&3===a.style.type&&u4(a,d));else if(e&16)a:if(!a.B.matches(e,c)&&(b=a.B,b.Xv=e,b.Ws=c,b.state=2,b=e&8?a.K:a.C,a.D=b,a.j.mode=1<<(a.G<<2)+(b.G<<1)+(4===b.style.type?1:0),(a.j.mode|1<<(a.G<<2)+(b.G<<1)+(4!==b.style.type?1:0))&a.j.B))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;Drb(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));x4(c,b,e)}}c.row=d;c.col=a+1}else switch(e&7){case 1:switch(c&112){case 32:w4(b.j,0,32);break a;case 48:57===c?(d=b.j,v4(d).j=0,32>d.col&&d.col++):w4(b.j,1,c&15)}break;case 2:c&32&&w4(b.j,2,c&31);break;case 3:c&32&&w4(b.j,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:Hrb(b);
break;case 33:d=b.j;1<d.col&&(--d.col,v4(d).j=0);break;case 36:d=b.j;b=v4(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:Grb(b,2,d);break;case 38:Grb(b,3,d);break;case 39:Grb(b,4,d);break;case 40:w4(b.j,0,32);break;case 41:b.style.set(2);b.j=b.B;b.j.j=0;b.j.style=b.style;b.C.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);Erb(d);Irb(b);break;case 43:Irb(b);break;case 44:a=b.B;switch(b.style.get()){case 1:case 2:case 3:u4(a,
d)}x4(a,0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.col=1;break b}break;case 3:}2>a.j&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;u4(a,d);Drb(a,b,b+1,a.j-1);x4(a,a.row,1)}break;case 46:x4(b.D,0,15);break;case 47:u4(b.B,d),b.D.updateTime(b.C.time+0),d=b.D,b.D=b.B,b.B=d,Hrb(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,32<(d.col+=c&3)&&(d.col=32)}}},Jrb=function(){},y4=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.bJ.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},Lrb=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.ag){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=Krb(l.textContent,n.textContent,p.textContent,f.textContent,h);return new y4(a,b,e,c,l,d,m)}switch(m.ag){case 9:case 10:m.No=1;break;case 11:m.No=2;break;case 12:m.No=3;break;case 13:m.No=4;break;case 14:m.No=5}return new y4(a,b,e,c,l.textContent||"",d,m)},Krb=function(a,b,c,d,e){var f=g.hB(),h=
f?g.yf("DIV"):g.yf("RUBY"),l=g.yf("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.yf("DIV"):g.yf("RP");a.textContent=b;h.appendChild(a);b=f?g.yf("DIV"):g.yf("RT");b.textContent=c;h.appendChild(b);c=e.ag;if(10===c||11===c||12===c||13===c||14===c)if(g.Hs(b,"text-emphasis-style","filled circle"),g.Hs(b,"text-emphasis-color","currentcolor"),g.Hs(b,"webkit-text-emphasis","filled circle"),11===e.ag||13===e.ag)g.Hs(b,"webkit-text-emphasis-position","under left"),g.Hs(b,"text-emphasis-position","under left");c=!0;if(4===e.ag||7===e.ag||12===e.ag||
14===e.ag)g.Hs(h,"ruby-position","over"),g.Hs(h,"-webkit-ruby-position","before");else if(5===e.ag||6===e.ag||11===e.ag||13===e.ag)g.Hs(h,"ruby-position","under"),g.Hs(h,"-webkit-ruby-position","after"),c=!1;e=f?g.yf("DIV"):g.yf("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.Hs(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.Hs(f,"display","none"),f=f.nextElementSibling,g.Hs(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Hs(h.lastElementChild,"display","none"),d?(g.Hs(h,"padding-top","0.6em"),g.Hs(f,"top","0")):(g.Hs(h,"padding-bottom","0.6em"),g.Hs(f,"bottom","0")));return h},z4=function(){g.I.apply(this,arguments)},A4=function(a,b,c,d,e){g.bJ.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},Mrb=function(a){var b="_"+B4++;
return new A4(0,0x8000000000000,0,b,a)},C4=function(a){z4.call(this);
this.C=a;this.pens={};this.N={};this.Z={};this.D="_"+B4++;this.K={};this.B=this.j=null;this.G=!0},D4=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},E4=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},F4=function(a,b){a=D4(a,b);
return void 0!==a?a:null},H4=function(a,b){a=a.getAttribute(b);
if(null!=a)return G4.test(a),a},Nrb=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.Z[d]:a.C);a=F4(b,"mh");null!=a&&(c.bB=a);a=F4(b,"ju");null!=a&&(c.textAlign=a);a=F4(b,"pd");null!=a&&(c.Ii=a);a=F4(b,"sd");null!=a&&(c.rT=a);a=H4(b,"wfc");null!=a&&(c.windowColor=a);b=D4(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},Orb=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.N[d]);a=F4(b,"ap");null!=a&&(c.gm=a);a=D4(b,"cc");null!=a&&(c.kt=a);a=D4(b,"ah");null!=a&&(c.gk=a);a=D4(b,"rc");null!=a&&(c.qs=a);b=D4(b,"av");null!=b&&(c.Po=b);return c},Prb=function(a,b,c,d){var e={};
Object.assign(e,Orb(a,b));Object.assign(e,Nrb(a,b));d?g.id(e,a.C)?(d=a.D,e=a.C):d="_"+B4++:d=b.getAttribute("id")||"_"+B4++;a=D4(b,"t")+c;b=D4(b,"d")||0x8000000000000;if(2===e.Ii||3===e.Ii)c=e.qs,e.qs=e.kt,e.kt=c;return new A4(a,b,0,d,e)},I4=function(a){z4.call(this);
this.G=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},J4=function(a){a=g.ze(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},Qrb=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.qs=a);b=b.ccColCount;void 0!==b&&(f.kt=b);if(2===f.Ii||3===f.Ii)b=f.qs,f.qs=f.kt,f.kt=b;return new A4(c,d,0,e,f)},K4=function(a,b,c,d){g.wV.call(this,a);
this.videoData=b;this.audioTrack=c;this.Ua=d;this.D=b.Bv},L4=function(a,b,c,d,e,f,h,l,m,n){p4.call(this,a,b,c,d,e,f,h,l,m,n);
this.type=1},M4=function(a,b,c){this.trackData=a;
this.K=c;this.version=this.G=this.C=this.byteOffset=0;this.j=new DataView(this.trackData);this.B=[]},N4=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},O4=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},P4=function(a,b){z4.call(this);
this.B=a;this.C=b;this.track="CC3"===this.C.languageName?4:0;this.j=new rrb;this.j.B=1<<this.track},Srb=function(a){if("string"===typeof a)return!1;
a=new M4(a,8,0);return Rrb(a)},Rrb=function(a){if(!(a.byteOffset<a.j.byteLength)||1380139777!==O4(a))return!1;
a.version=N4(a);if(1<a.version)return!1;N4(a);N4(a);N4(a);return!0},Q4=function(a,b,c,d,e,f,h,l,m,n){p4.call(this,a,b,c,d,e,f,h,l,m,n);
var p=this;this.type=2;this.Ca=[];this.qa=this.Y=this.Sa=0;this.Fa=NaN;this.Kb=0;this.Tb=null;this.Wa=new g.wv(this.Fba,433,this);this.G&&(n.createClientVe(this.G,this,167342),this.T(this.G,"click",function(){n.logClick(p.G)}),a=new g.TU(this.element,!0),g.N(this,a),a.subscribe("hoverstart",function(){n.logVisibility(p.G,!0)},this));
g.Ev(this.element,"ytp-caption-window-rollup");g.N(this,this.Wa);g.Hs(this.element,"overflow","hidden")},Trb=function(a,b){if(!b)return"";
a.C&&1!==a.B.params.rT&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},Urb=function(a){a.Ca=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.B.params.qs,c=0,d=0,e=a.Ca.length-1;c<b&&-1<e;){var f=a.Ca[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.Y=d;b=Math;c=b.max;isNaN(a.Fa)&&((d=a.j.kt)?(e=g.yf("SPAN"),g.Kf(e,"\u2013".repeat(d)),g.Hs(e,mrb(a,a.j.Pe)),a.D.appendChild(e),a.Fa=e.offsetWidth,a.D.removeChild(e)):a.Fa=0);d=a.D;a.qa=c.call(b,a.Fa,a.Kb,(a.C?d.offsetHeight:d.offsetWidth)+1)},Vrb=function(a,b){Urb(a);
var c=a.Ca.reduce(function(f,h){return(a.C?h.offsetWidth:h.offsetHeight)+f},0);
c=a.Y-c;if(c!==a.Sa){var d=0<c&&0===a.Sa,e=c<a.Sa;b||isNaN(c)||d||!e||(g.Ev(a.element,"ytp-rollup-mode"),g.xv(a.Wa));g.Hs(a.D,"transform",Trb(a,c));a.Sa=c}Urb(a)},R4=function(){z4.call(this)},Wrb=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new y4(b,c,d,e.id,p.nodeValue,f||0<n,g.gd(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);Wrb(a,b,c,d,e,!0,p,q,m)}}},Xrb=function(a){var b=a.split(":");
a=0;b=g.u(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},Yrb=function(a,b,c,d){d=Object.assign({bB:0},d);
return new A4(a,b,c,"_"+B4++,d)},S4=function(a,b){g.I.call(this);
this.J=a;this.W=b;this.j=null;this.B=this.J.dA()},Zrb=function(a){if("string"===typeof a||Srb(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.JP(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.KN(a)},asb=function(a,b,c){if("string"===typeof b||Srb(b))return[{trackData:b,
lT:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.pRa(d);if(a.B&&e){var f=g.gRa(e),h=g.hRa(e);e=e.zl;f&&e&&a.B.sH(e,f,h)}a=g.QP(d,1835295092);if(!a||!a.length||!a[0].size)return[];f=[];for(h=0;h<a.length;h++)e=a[h],e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.KN(e),f.push({trackData:e,lT:c+1E3*h});$rb(d,f,c);return f=f.filter(function(l){return!!l.trackData})},$rb=function(a,b,c){var d=g.JP(a,0,1836476516),e=9E4;
d&&(e=g.KP(d)||9E4);d=0;for(var f=g.QP(a,1836019558),h=0;h<f.length;h++){var l=f[h];h<b.length&&(l=g.JP(a,l.dataOffset,1953653094))&&(l=g.JP(a,l.dataOffset,1952867444))&&(l=g.mRa(l)/e*1E3,0===h&&(d=l),b[h].lT=l-d+c||c*h*1E3)}},bsb=function(a,b,c,d,e){if(!Srb(c))throw Error("Invalid binary caption track data");
a.j||(a.j=new P4(e,b));return a.j.Do(c,d)},csb=function(a,b,c){a.j||(a.j=new R4);
a=a.j.Do(b,c);.01>Math.random()&&g.BE(Error("Deprecated subtitles format in web player: WebVTT"));return a},esb=function(a,b,c,d){if("{"===c[0])try{return a.j||(a.j=new I4(dsb(b))),a.j.Do(c,d)}catch(f){return g.AE(f),[]}var e=g.c2(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.j||(a.j=new C4(dsb(b),a.W)),a.j.Do(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},dsb=function(a){var b=
{};
if(a=g.hS(a))b.lang=a,g.elb.test(a)&&(b.Ii=1);return b},T4=function(a){g.tV.call(this,a);
var b=this;this.J=a;this.W=this.J.U();this.videoData=this.J.getVideoData();this.zb=this.J.ob();var c;this.gb=null==(c=this.J.getVideoData(1))?void 0:g.rT(c);this.C={Pe:{}};this.G={Pe:{}};this.Ha=[];this.ra={};this.Va={};this.Y=!1;this.Nb=g.sT(this.videoData);this.bb=g.n_a(this.videoData,this.J);this.Kb=!!this.videoData.captionTracks.length;this.Tb=!!this.videoData.Rd;this.Wa="3"===this.W.controlsType;this.j=this.N=this.Z=this.Sa=this.rb=null;this.eb=new S4(this.J,this.W);this.B=null;this.Ca=new g.XJ(this);
this.K=new g.W({I:"div",S:"ytp-caption-window-container",X:{id:"ytp-caption-window-container"}});this.qa={top:0,right:0,bottom:0,left:0,width:1,height:1};c=null;var d=g.gw("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Yv(d));this.storage=c;var e;this.Jb=!(null==(e=a.Re())||!e.jH());this.D=fsb(this);this.Fa=!this.D&&this.Wa&&this.Jb&&this.bb;g.N(this,this.eb);this.D?this.Na=this.La=null:(this.La=new g.vv(this.ET,void 0,this),g.N(this,this.La),this.Na=new g.wv(this.fda,2E3,this),g.N(this,
this.Na));g.N(this,this.Ca);g.TT(this.player,this.K.element,4);g.N(this,this.K);this.D||this.Ca.T(a,"resize",this.HT);(this.Hb=g.ER(this.W)&&!g.xB()&&!this.J.isFullscreen()&&!this.D&&!this.Fa)&&this.Ca.T(a,"resize",this.Maa);this.Ca.T(a,"onPlaybackAudioChange",this.Y$);this.Ca.T(a,g.cJ("captions"),function(f){b.onCueRangeEnter(f)});
this.Ca.T(a,g.dJ("captions"),function(f){b.onCueRangeExit(f)});
this.gb&&this.Ca.T(a,"videodatachange",function(f,h){b.onVideoDataChange(f,h)});
gsb(this,Zqb()||{});this.player.Cc("onCaptionsModuleAvailable")},jsb=function(a){if(1===a.W.Jb||1===a.videoData.BH||"alwayson"===g.aT(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.getAudioTrack().B;if(2===a.W.Jb){if(g.QR(a.W))var c=hsb(a);else if(a.storage)try{c=a.storage.get("module-enabled")}catch(e){a.storage.remove("module-enabled")}else c=null;if(null!=c)return!!c}c=Sqb(a.player.getAudioTrack(),g.QR(a.W));var d=g.aT(a.videoData,"yt:cc");if(void 0===isb(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===d;return"ON"===b||"on"===
g.aT(a.videoData,"yt:cc")},U4=function(a,b){if(a.B&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.getAudioTrack();return!!a.j||"FORCED_ON"===a.B},isb=function(a){var b=void 0,c=g.VB(g.UB(),65);
if(g.QR(a.W)&&null!=c){if(null!=hsb(a))return!1;b=!c}return b},ksb=function(a){var b;
a.Nb?b=new K4(a.W,a.videoData,a.getAudioTrack(),a.player):a.bb?b=new o4(a.videoData.j,a.player):a.Kb?b=new g.xV(a.W,a.videoData,a.getAudioTrack()):b=new g.BV(a.W,a.videoData.Rd,a.videoData.videoId,g.gXa(a.videoData),a.videoData.dn,a.videoData.eventId);return b},W4=function(a,b){if(a.j){if(a.N&&a.N.D)return a.N.D;
g.mT(a.videoData)&&(b=!0);b||(b=a.Tb?!1:a.Kb?!1:!0);b=b||lsb(a);b=g.uV(a.j.B,b);var c=null;if(g.QR(a.W)){var d=a.J.isInline()?void 0:g.QB("yt-player-caption-sticky-language");for(var e=[d,a.videoData.captionsLanguagePreference,a.W.captionsLanguagePreference,g.aT(a.videoData,"yt:cc_default_lang")],f=!1,h=0;h<e.length;h++){var l=e[h];if(l){f=!0;for(var m=0;m<b.length;m++)if(g.hS(b[m])===l)return b[m];for(m=0;m<b.length;m++)if(g.hS(b[m]).split("-")[0]===l.split("-")[0])return b[m]}}if(f&&a.j&&(e=a.j.D,
e.length))for(e=g.u(e),f=e.next();!f.done;f=e.next())if(f=f.value,f.languageCode===d){c=f;break}}else for(d=[a.videoData.captionsLanguagePreference,a.W.captionsLanguagePreference,g.aT(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(f=0;f<b.length;f++)if(g.hS(b[f])===d[e])return b[f];d=null;a.N&&a.N.C&&(d=a.N.C);d||(d=b.find(function(n){return n.isDefault})||null);
d||(d=b[0]||V4(a));d&&c&&g.hS(d).split("-")[0]!==c.languageCode.split("-")[0]&&(d=Tqb(d,c));return d}return null},V4=function(a){return a.N&&a.N.j},X4=function(a){var b=V4(a);
return!!b&&a.B===b},msb=function(a){var b=Sqb(a.player.getAudioTrack(),g.QR(a.W)),c;
"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=W4(a,a.Y):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&U4(a)?c=V4(a):isb(a)||a.Y||jsb(a)?c=W4(a,a.Y):U4(a)&&(c=V4(a));if(a.D||a.Fa){var d=g.uV(a.j.B,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.yf("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.fS(f));h.setAttribute("srclang",g.hS(f));h.setAttribute("id",f.toString());a.Fa||h.setAttribute("src",a.j.Kw(f,"vtt"));f===c&&h.setAttribute("default","1");b.push(h)}c=a.J.Re();c.HD(b);c=
c.Ib();a.Jb&&a.Ca.T(c.textTracks,"change",a.lca)}else!a.B&&c&&Y4(a,c),a.player.Cc("onCaptionsTrackListChanged"),a.player.Mm("onApiChange")},nsb=function(a,b){var c=a.J.Re().Ib().textTracks;
a=a.B.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},Y4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.Y=c,a.Y&&(g.QR(a.W)?Z4(a,!!b):$4(a,!!b)));a.B=b;U4(a)&&(a.B=V4(a));var d;osb(a,null!=(d=a.B)?d:void 0);a.load()},qsb=function(a,b){if(b instanceof A4){var c=a.ra[b.id];
c&&c.B!==b&&(c.dispose(),delete a.ra[b.id],c=null);c||(c=psb(a,b))&&(a.ra[b.id]=c)}else c=b.windowId,a.Va[c]||(a.Va[c]=[]),a.Va[c].push(b)},psb=function(a,b){var c=rsb(a);
if(!c)return null;var d=a.B?g.hS(a.B):null;d&&g.elb.test(d)&&(b.params.Ii=1);var e=a.zb.getPlayerSize();d=e.height*a.qa.height;e=e.width*a.qa.width;"google-live"!==a.W.playerStyle||a.C.isDefault||Object.assign(b.params,a.C);switch(null!=b.params.bB?b.params.bB:1<b.j.length?1:0){case 1:return new L4(b,a.C,a.G,c.width,c.height,e,d,a.W.experiments,a.FM.bind(a),a.J);case 2:return new Q4(b,a.C,a.G,c.width,c.height,e,d,a.W.experiments,a.FM.bind(a),a.J);default:return new p4(b,a.C,a.G,c.width,c.height,e,
d,a.W.experiments,a.FM.bind(a),a.J)}},gsb=function(a,b,c){c=void 0===c?!1:c;
var d=a5.Pe;a.C={};Object.assign(a.C,a5);a.C.Pe={};Object.assign(a.C.Pe,d);a.G={Pe:{}};var e=b.backgroundOverride?a.G:a.C,f=b.background||d.background;G4.test(f);e.Pe.background=f;e=b.colorOverride?a.G:a.C;f=b.color||d.color;G4.test(f);e.Pe.color=f;e=b.windowColorOverride?a.G:a.C;f=b.windowColor||a5.windowColor;G4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.G:a.C;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Pe.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.G:a.C;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.Pe.fontSizeIncrement=f;f=b.fontStyleOverride?a.G:a.C;e=b.fontStyle;null==e&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.Pe;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.G:a.C;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Pe.textOpacity=f;e=b.windowOpacityOverride?a.G:a.C;f=b.windowOpacity;null==f&&(f=a5.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.G:a.C;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Pe.charEdgeStyle=f;e=b.fontFamilyOverride?a.G:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Pe.fontFamily=f;a.loaded&&a.HT();c&&g.PB("yt-player-caption-display-settings",b,2592E3)},tsb=function(a,b,c){b&&!a.Z?(b=Mrb({Ii:0,
lang:"en-GB"}),a.Z=[b,new y4(b.start,b.end-b.start,0,b.id,null!=c?c:"Captions look like this")],a.player.gf(a.Z)):!b&&a.Z&&(ssb(a,a.Z),a.Z=null)},ssb=function(a,b){a.player.Lo(b);
b=g.u(b);for(var c=b.next();!c.done;c=b.next())g.Hb(a.Ha,c.value);m4(a.La)},osb=function(a,b){a.W.L("html5_modify_caption_vss_logging")&&(a.videoData.lD=b)},rsb=function(a){var b=a.zb.getVideoContentRect(!0).height,c=a.zb.getVideoContentRect(!0).width;
if(!b||!c)return null;b*=a.qa.height;c*=a.qa.width;return{width:c,height:b}},$4=function(a,b){if(a.storage)try{a.storage.set("module-enabled",b)}catch(c){}},Z4=function(a,b){a.J.isInline()||g.PB("yt-player-sticky-caption",b,2592E3)},hsb=function(a){if(!a.J.isInline())return g.QB("yt-player-sticky-caption")},fsb=function(a){var b,c=!(null==(b=a.J.Re())||!b.iH());
return a.Wa&&c&&!a.bb},lsb=function(a){return a.W.L("web_deprecate_always_includes_asr_setting")&&g.QR(a.W)?!0:!!g.VB(g.UB(),66)};
g.fY.prototype.yE=g.fa(44,function(a){var b=2;this.K.has(a)?b=0:g.V5a(this,a)&&(b=1);return b});
g.A_.prototype.yE=g.fa(43,function(a){return this.Vc.yE(a)});
g.fY.prototype.sH=g.fa(42,function(a,b,c){this.La.set(a,{zt:b,lz:c})});
g.A_.prototype.sH=g.fa(41,function(a,b,c){this.Vc.sH(a,b,c)});
g.wV.prototype.bS=g.fa(40,function(){return!1});
g.wV.prototype.pu=g.fa(39,function(){});
g.xV.prototype.pu=g.fa(38,function(a,b,c){var d=this;this.Ma();b=this.Kw(a,b);this.Js();this.j=g.VA(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.BV.prototype.pu=g.fa(37,function(a,b,c){var d=this;this.Ma();b=this.Kw(a,b);this.Js();this.j=g.VA(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.$U.prototype.zz=g.fa(36,function(){for(var a=g.of(document,"track",void 0,this.j),b=0;b<a.length;b++)g.Hf(a[b])});
g.KX.prototype.zz=g.fa(35,function(){this.mediaElement.zz()});
g.$U.prototype.jH=g.fa(34,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.KX.prototype.jH=g.fa(33,function(){return this.mediaElement.jH()});
g.$U.prototype.iH=g.fa(32,function(){return!!this.j.textTracks});
g.KX.prototype.iH=g.fa(31,function(){return this.mediaElement.iH()});
g.$U.prototype.HD=g.fa(30,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.KX.prototype.HD=g.fa(29,function(a){this.mediaElement.HD(a)});
g.v_.prototype.OE=g.fa(19,function(){return this.N});
g.H0.prototype.OE=g.fa(18,function(){var a;return(null==(a=g.GT(this))?void 0:a.dA())||null});
g.MT.prototype.dA=g.fa(17,function(){return this.app.OE()});
g.w0.prototype.dA=g.fa(16,function(){var a;return(null==(a=this.ya)?void 0:a.OE())||null});
g.yP.prototype.AJ=g.fa(2,function(a){return(a=this.Hn(a))?a.j:0});
g.ASa.prototype.AJ=g.fa(1,function(){return 0});
var Xqb=/#(.)(.)(.)/,Wqb=/^#(?:[0-9a-f]{3}){1,2}$/i,drb={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",
la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",
mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",
naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",
or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",
ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",
shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",
sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",
tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",
xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};
n4.prototype.contains=function(a){a=g.Sb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
n4.prototype.length=function(){return this.segments.length/2};
g.y(arb,g.I);g.k=arb.prototype;g.k.va=function(){g.I.prototype.va.call(this);this.C&&this.C.cancel()};
g.k.oB=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Lc();var b=this.j;this.j=g.Bb(this.qa.Br(a).ib);b!==this.j&&this.Y&&this.Y()};
g.k.reset=function(){this.D=new n4;this.K=-1;this.C&&(this.C.cancel(),this.C=null)};
g.k.AZ=function(){this.Ma();var a;if(a=null!=this.j)a=this.j,a=a.j.Rs(a);if(a&&!this.C&&!(this.j&&30<this.j.startTime-this.player.getCurrentTime())){a=this.j;a=a.j.hD(a);var b=a.ib[0],c;if(null==(c=this.player.getVideoData())?0:c.enableServerStitchedDai)if(c=this.player.dA()){var d=b.j.info.id,e=b.Pa,f=a.ib[0].C;if(this.policy.Ha){if(c=c.DJ(f,e,d,3))a.D=c}else if(d=c.Xz(f,e,d,3))if(c=c.yE(e),0===c)d&&(a.j=new g.rP(d));else if(2===c){this.N.start();brb(this)&&this.seekTo(this.player.getCurrentTime());
return}}b.j.index.Rn(b.Pa)?(this.D.contains(a.ib[0].Pa)||crb(this,a),this.j=g.Bb(a.ib)):brb(this)&&this.seekTo(this.player.getCurrentTime())}this.N.start()};
g.y(o4,g.wV);g.k=o4.prototype;g.k.pu=function(a,b,c){var d=this;this.Js();b=frb(this,a.getId());b||(b=a.languageCode,b=this.j.isManifestless?grb(this,b,"386"):grb(this,b));if(b){var e=1E3*(b.index.AJ(b.index.Jn())-b.index.getStartTime(b.index.Jn())),f=new g.j_a(this.W),h=function(){d.C&&d.C.reset();d.G=!0};
this.W.L("html5_keep_caption_data_after_seek")&&(h=null);this.C=new arb(f,this.J,b,function(l,m){c(l,a,m,e)},this.K||g.hK(b.info),h)}};
g.k.bS=function(){var a=this.G;this.G=!1;return a};
g.k.OA=function(a){var b=this.K?[new g.eS({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.eS({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.j.isManifestless?erb(this,"386"):erb(this);b=g.u(b);for(var c=b.next();!c.done;c=b.next())g.vV(this.B,c.value);a()};
g.k.Js=function(){this.C&&(this.C.dispose(),this.C=null)};
g.k.Kw=function(){return""};
var G4=/^#(?:[0-9a-f]{3}){1,2}$/i;var krb=["left","right","center","justify"];g.y(p4,g.W);g.k=p4.prototype;g.k.z4=function(a,b){this.bb=a;this.gb=b;var c=g.Rs(this.element,this.element.parentElement);this.rb=a-c.x;this.zb=b-c.y};
g.k.y4=function(a,b){if(a!==this.bb||b!==this.gb){g.Dv(this.element,"ytp-dragging")||g.Ev(this.element,"ytp-dragging");var c=g.Ts(this.element);a=a-this.rb-.02*this.playerWidth;var d=b-this.zb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.ze(e,0,2));var f=(d+c.height/2)/this.maxHeight*3;f=Math.floor(g.ze(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.ze(a,0,1);c=(d+f/2*c.height)/this.maxHeight;c=100*g.ze(c,0,1);this.B.params.gm=b;this.B.params.Po=c;this.B.params.gk=
a;this.B.params.isDefault=!1;this.j.gm=b;this.j.Po=c;this.j.gk=a;this.j.isDefault=!1;this.ra.gm=b;this.ra.Po=c;this.ra.gk=a;this.ra.isDefault=!1;this.Q0()}};
g.k.x4=function(){g.Gv(this.element,"ytp-dragging")};
g.k.Q0=function(){this.cC(this.K)};
g.k.getType=function(){return this.type};
g.k.cC=function(a){var b=this.Hb?0:Math.min(this.TX(),this.maxWidth),c=this.SX(),d=this.Hb;if(d){var e=getComputedStyle(this.D.parentNode);e=q4(e.borderLeftWidth)+q4(e.borderRightWidth)+q4(e.paddingLeft)+q4(e.paddingRight)}else e=0;var f=e;e="";3===this.B.params.Ii&&(e="rotate(180deg)");var h=d?"calc(96% - "+f+"px)":"96%";g.Hs(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":h,"max-height":h,margin:"",transform:""});this.FN(a);e={transform:e,top:"",left:"",
width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var l=.96*this.j.gk+2;h=this.j.gm;switch(h){case 0:case 3:case 6:(d=this.j.Pe.fontSizeIncrement)&&0<d&&2!==this.j.Ii&&3!==this.j.Ii&&(l=Math.max(l/(1+2*d),2));e.left=l+"%";break;case 1:case 4:case 7:e.left=l+"%";l=this.D.offsetWidth;b||l?(b=b||l+1,e.width=b+"px",e["margin-left"]=d?b/-2-f/2+"px":b/-2+"px"):e.transform+=" translateX(-50%)";break;case 2:case 5:case 8:e.right=100-l+"%"}d=.96*this.j.Po+2;switch(h){case 0:case 1:case 2:e.top=
d+"%";break;case 3:case 4:case 5:e.top=d+"%";(c=c||this.element.clientHeight)?(e.height=c+"px",e["margin-top"]=c/-2+"px"):e.transform+=" translateY(-50%)";break;case 6:case 7:case 8:e.bottom=100-d+"%"}g.Hs(this.element,e);if(this.G){c=this.D.offsetHeight;d=1;for(b=0;b<a.length;b++)e=a[b],"string"===typeof e.text&&(d+=e.text.split("\n").length-1,e.append||0===b||d++);c/=d;this.G.style.height=c+"px";this.G.style.width=c+"px";this.element.style.paddingLeft=c+5+"px";this.element.style.paddingRight=c+
5+"px";a=Number(this.element.style.marginLeft.replace("px",""))-c-5;c=Number(this.element.style.marginRight.replace("px",""))-c-5;this.element.style.marginLeft=a+"px";this.element.style.marginRight=c+"px"}};
g.k.FN=function(a){var b;for(b=0;b<a.length&&a[b]===this.K[b];b++);if(this.Ha||this.K.length>b)b=0,this.Ha=!1,this.K=[],this.N=this.Na=this.La=null,g.Cf(this.D);for(;b<a.length;b++)prb(this,a[b])};
g.k.TX=function(){return 0};
g.k.SX=function(){return 0};
g.k.toString=function(){return g.W.prototype.toString.call(this)};rrb.prototype.clear=function(){this.C=this.time=this.mode=0;this.j=[];this.reset()};
rrb.prototype.reset=function(){this.mode=0;this.D.reset(0);this.G.reset(1)};
var srb=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];r4.prototype.set=function(a){this.type=a};
r4.prototype.get=function(){return this.type};
s4.prototype.clear=function(){this.state=0};
s4.prototype.update=function(){this.state=2===this.state?1:0};
s4.prototype.qe=function(){return 0!==this.state};
s4.prototype.matches=function(a,b){return this.qe()&&a===this.Xv&&b===this.Ws};
xrb.prototype.reset=function(){this.timestamp=this.j=0};
t4.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
t4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.j?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
t4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.j=0;this.col=this.row=1};
var yrb=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],zrb=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Arb=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Brb=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];Frb.prototype.reset=function(a,b){this.G=b;this.style.set(2);this.B=this.K;this.D=this.N;this.j=this.B;var c=(a<<2)+(b<<1);this.K.reset(c);this.N.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
qrb.prototype.reset=function(a){this.G=a;this.B.clear();this.D=this.C;this.C.reset(a,0);this.K.reset(a,1)};Jrb.prototype.D=function(){};g.y(y4,g.bJ);y4.prototype.toString=function(){return g.bJ.prototype.toString.call(this)};g.y(z4,g.I);z4.prototype.Do=function(){return[]};
z4.prototype.reset=function(){};g.y(A4,g.bJ);A4.prototype.toString=function(){return g.bJ.prototype.toString.call(this)};
var B4=0;g.y(C4,z4);C4.prototype.reset=function(){this.K={};this.B=this.j=null;this.G=!0};
C4.prototype.Do=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.u(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.u(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=E4(a,"b");
null!=l&&(h.bold=l);l=E4(a,"i");null!=l&&(h.italic=l);l=E4(a,"u");null!=l&&(h.underline=l);l=F4(a,"et");null!=l&&(h.charEdgeStyle=l);l=F4(a,"of");null!=l&&(h.offset=l);l=H4(a,"bc");null!=l&&(h.background=l);l=H4(a,"ec");null!=l&&(h.aO=l);l=H4(a,"fc");null!=l&&(h.color=l);l=F4(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=D4(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=D4(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=D4(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=F4(a,"rb");null!=l&&10!==l&&
0!==l&&(h.ag=10<l?l-1:l);a=F4(a,"hg");null!=a&&(h.LY=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.Z[c]=Nrb(this,a);break;case "wp":c=a.getAttribute("id"),this.N[c]=Orb(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.u(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.j=Prb(this,a,b,!1);(a=this.K[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.K[this.j.id]=this.j;d.push(this.j);break;case "p":var m=a;l=b;c=[];f=m.getAttribute("w")||
this.D;h=!!E4(m,"a");l=(D4(m,"t")||0)+l;var n=D4(m,"d")||5E3;h||(!this.G&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&"\n"===this.B.text&&(this.B.text=""));var p=h?6:5,q=m.getAttribute("p");q=q?this.pens[q]:null;var r=Array.from(m.childNodes);r.length&&(this.G=null!=m.getAttribute("d"));for(m=0;m<r.length;m++){var t=r[m],v=void 0;0<m&&(h=!0);var w=void 0;1===t.nodeType&&(w=t);if(w&&"s"===w.tagName){if((t=(t=w.getAttribute("p"))?this.pens[t]:null)&&t.ag&&(1===t.ag?(t=r.slice(m,
m+4),4===t.length&&(v=Lrb(l,n,f,h,p,t,this.pens),m+=3)):v=Lrb(l,n,f,h,p,[w],this.pens)),!v){var A=w;v=l;w=n;t=f;var C=h,F=p,H=A.textContent?A.textContent:"",L=A.getAttribute("p");L=L?this.pens[L]:null;A=D4(A,"t")||0;v=new y4(v+A,w-A,F,t,H,C,L)}}else v=new y4(l,n,p,f,t.textContent||"",h,q);c.push(v);this.B=v}if(0<c.length)for(c[0].windowId===this.D&&(this.j=Prb(this,a,b,!0),d.push(this.j)),a=g.u(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var usb=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.y(I4,z4);I4.prototype.reset=function(){this.B.clear()};
I4.prototype.Do=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.u(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.aO=J4(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=J4(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=J4(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.ag=10<h?h-1:h,f.No=usb.get(f.ag));e.hgHorizGroup&&(f.LY=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.u(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.G),void 0!==e.mhModeHint&&(f.bB=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.Ii=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.rT=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=J4(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.u(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),void 0!==e.ahHorPos&&
(f.gk=e.ahHorPos),void 0!==e.apPoint&&(f.gm=e.apPoint),void 0!==e.avVerPos&&(f.Po=e.avVerPos),void 0!==e.ccCols&&(f.kt=e.ccCols),void 0!==e.rcRows&&(f.qs=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.u(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;e=(l.tStartMs||0)+b;f=l.dDurationMs||0;if(l.id)h=String(l.id),d=Qrb(this,l,e,f,h),a.push(d),this.B.set(h,d);else{l.wWinId?h=l.wWinId.toString():(h="_"+B4++,d=Qrb(this,l,e,f,h),a.push(d),this.B.set(h,d));d=a;var m=l;0===f&&(f=5E3);l=this.B.get(h);
var n=!!m.aAppend,p=n?6:5,q=m.segs,r=null;m.pPenId&&(r=this.j.get(m.pPenId));for(m=0;m<q.length;m++){var t=q[m],v=t.utf8;if(v){var w=t.tOffsetMs||0,A=null;t.pPenId&&(A=this.j.get(t.pPenId));if(2===(null!=l.params.bB?l.params.bB:1<l.j.length?1:0)&&n&&"\n"===v)continue;t=null;var C=[],F;if(F=A&&1===A.ag){F=q;var H=m;if(H+3>=F.length||!F[H+1].pPenId||!F[H+2].pPenId||!F[H+3].pPenId)F=!1;else{var L=F[H+1].pPenId;(L=this.j.get(L))&&L.ag&&2===L.ag?(L=F[H+2].pPenId,L=this.j.get(L),!L||!L.ag||3>L.ag?F=!1:
(L=F[H+3].pPenId,F=(L=this.j.get(L))&&L.ag&&2===L.ag?!0:!1)):F=!1}}if(F)w=q[m+1].utf8,t=q[m+3].utf8,F=q[m+2].utf8,H=this.j.get(q[m+2].pPenId),v=Krb(v,w,F,t,H),t=new y4(e,f,p,h,v,n,A),m+=3;else{if(-1<v.indexOf("<")){var M=void 0;C=A;F=r;H=e;L=f;var R=w,ea=p,ma=n,ka=[],ia=g.c2("<html>"+v+"</html>");if(!ia.getElementsByTagName("parsererror").length&&(null==(M=ia.firstChild)?0:M.childNodes.length))for(M=g.u(ia.firstChild.childNodes),ia=M.next();!ia.done;ia=M.next()){ia=ia.value;var sa=void 0,aa=void 0,
U=null!=(aa=null==(sa=ia.textContent)?void 0:sa.replace(/\n/g,""))?aa:"";if(3!==ia.nodeType||U&&null==U.match(/^ *$/)){sa={};Object.assign(sa,C||F);aa=void 0;switch(null==(aa=ia)?void 0:aa.tagName){case "b":sa.bold=!0;break;case "i":sa.italic=!0;break;case "u":sa.underline=!0}ka.push(new y4(H+R,L-R,ea,l.id,U,ma,sa))}}C=ka}C.length||(C=[new y4(e+w,f-w,p,l.id,v,n,A||r)])}if(C.length)for(n=g.u(C),A=n.next();!A.done;A=n.next())A=A.value,d.push(A),l.j.push(A);else t&&(d.push(t),l.j.push(t))}n=!0}}}b=a}else b=
[];return b};g.y(K4,g.wV);K4.prototype.pu=function(a,b,c){Vqb(this.videoData.videoId,a.vssId,c)};
K4.prototype.OA=function(a){if(this.audioTrack)for(var b=g.u(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.vV(this.B,c.value);a()};g.y(L4,p4);L4.prototype.FN=function(a){var b=this.B.j;p4.prototype.FN.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,vsb);var e=c.j;var f=d}prb(this,c,d)}};
var vsb={C9:!0};g.y(M4,Jrb);M4.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+B4++;c=c/1E3-this.K;d=d/1E3-this.K;a=new A4(c,d-c,5,f,{textAlign:0,gm:0,gk:2.5*b,Po:5.33*a});e=new y4(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.y(P4,z4);P4.prototype.Do=function(a){a=new M4(a,a.byteLength,this.B);if(Rrb(a)){for(;a.byteOffset<a.j.byteLength;)for(0===a.version?a.C=O4(a)*(1E3/45):1===a.version&&(a.C=4294967296*O4(a)+O4(a)),a.G=N4(a);0<a.G;a.G--){var b=N4(a),c=N4(a),d=N4(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.j,b.j.push({time:a.C,type:this.track,MW:c,NW:d,order:b.j.length}))}wrb(this.j,a);return a.B}return[]};
P4.prototype.reset=function(){this.j.clear()};g.y(Q4,p4);g.k=Q4.prototype;g.k.Q0=function(){g.yv(this.Wa)};
g.k.Fba=function(){g.Gv(this.element,"ytp-rollup-mode");this.cC(this.Tb,!0)};
g.k.SX=function(){return this.C?this.qa:this.Y};
g.k.TX=function(){return this.C?this.Y:this.qa};
g.k.cC=function(a,b){this.Tb=a;if(this.B.params.qs){for(var c=0,d=0;d<this.K.length&&c<a.length;d++)this.K[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.K.concat(a.slice(c)));this.Kb=this.qa;this.Y=this.qa=0;p4.prototype.cC.call(this,a);Vrb(this,b)}p4.prototype.cC.call(this,a)};g.y(R4,z4);
R4.prototype.Do=function(a,b){var c=[];a=a.split(wsb);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!xsb.test(e)){var h=ysb.exec(e);if(h&&4<=h.length){var l=Xrb(h[1]),m=Xrb(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var r=null,t="";n=g.u(n);for(var v=n.next();!v.done;v=n.next())if(v=v.value.split(":"),2===v.length){var w=v[1];switch(v[0]){case "line":v=w.split(",");v[0].endsWith("%")&&(p=v[0],h.Po=Number.parseInt(p,10),2===v.length&&(q=v[1].trim()));break;case "position":v=
w.split(",");r=v[0];h.gk=Number.parseInt(r,10);2===v.length&&(t=v[1].trim());break;case "align":switch(w){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!r)switch(h.textAlign){case 0:h.gk=0;break;case 1:h.gk=100;break;case 2:h.gk=50}if(null!=h.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(t){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;h.gm=q}e=e.substring(ysb.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=Yrb(l,m,5,t),m=new y4(l,m,5,f.id,h,!1,g.gd(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(zsb),1===q.length?(h=5,t=Yrb(l,m,h,t)):(p=h=6,t=Object.assign({kt:32},t),t=new A4(l,m,p,"_"+B4++,t)),c.push(t),p=l,r=0;r<q.length;r++)n=q[r],0===r%2?(v=g.c2("<html>"+n+"</html>"),v.getElementsByTagName("parsererror").length?
(w=v.createElement("span"),w.appendChild(v.createTextNode(n))):w=v.firstChild,Wrb(this,p,m-(p-l),h,t,0<r,w,e,c)):p=Xrb(n)+f}ysb.lastIndex=0}}return c};
var xsb=/^NOTE/,wsb=/(?:\r\n|\r|\n){2,}/,ysb=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),zsb=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.LX.WJ(R4,{Do:"wvppt"});g.y(S4,g.I);
S4.prototype.Do=function(a,b,c,d){c=c||0;d=d||0;if(this.B&&a){a:{var e=d,f=asb(this,a,c),h=[];try{for(var l=g.u(f),m=l.next();!m.done;m=l.next()){var n=m.value,p=n.trackData,q=n.lT;h="string"!==typeof p?h.concat(bsb(this,b,p,q,e)):"WEBVTT"===p.substring(0,6)?h.concat(csb(this,p,q)):h.concat(esb(this,b,p,q))}var r=h;break a}catch(t){g.AE(t);this.clear();r=[];break a}r=void 0}if(0!==r.length)return r}a=Zrb(a);if(!a)return[];try{return"string"!==typeof a?bsb(this,b,a,c,d):"WEBVTT"===a.substring(0,6)?
csb(this,a,c):esb(this,b,a,c)}catch(t){return g.AE(t),this.clear(),[]}};
S4.prototype.clear=function(){this.j&&this.j.dispose();this.j=null};
S4.prototype.reset=function(){this.j&&this.j.reset()};
S4.prototype.va=function(){g.I.prototype.va.call(this);this.clear()};var a5={windowColor:"#080808",windowOpacity:0,textAlign:2,gm:7,gk:50,Po:100,isDefault:!0,Pe:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.y(T4,g.tV);g.k=T4.prototype;g.k.va=function(){if(this.D||this.Fa){var a=this.J.Re();a&&!a.Ma()&&a.zz()}else tsb(this,!1);g.tV.prototype.va.call(this)};
g.k.bT=function(){return this.W.L("html5_honor_caption_availabilities_in_audio_track")&&!this.bb};
g.k.Qu=function(){if(this.Wa)return this.D||this.Fa;var a=this.getAudioTrack();if(this.bT()){if(!a.captionTracks.length)return!1;if(!this.j)return!0}a=Sqb(a,g.QR(this.W));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?U4(this):isb(this)||U4(this)?!0:jsb(this)};
g.k.load=function(){var a=this;g.tV.prototype.load.call(this);this.N=this.getAudioTrack();this.j?this.B&&(this.eb.clear(),this.D?nsb(this,!0):3!==this.player.getPresentingPlayerType()&&this.j.pu(this.B,"json3",function(b,c,d,e){if(b){var f;osb(a,null!=(f=a.B)?f:void 0);a.j.bS()&&(a.Ha=[],a.J.nf("captions"),m4(a.La),a.eb.reset());if(a.videoData.Qf){var h;d=(null!=(h=d)?h:0)+a.videoData.Qf}b=a.eb.Do(b,c,d,e);if(a.gb)for(c=g.u(b),e=c.next();!e.done;e=c.next())e=e.value,e.C=a.videoData.clientPlaybackNonce,
e.rl=a.videoData.Qf;c=!a.W.L("html5_keep_caption_data_after_seek")&&a.bb;a.player.gf(b,void 0,c);!a.Y||a.Fa||X4(a)||!a.W.Ym||g.HI(a.W)||g.GR(a.W)||g.bG(a.W)||"shortspage"===a.W.La||a.player.isInline()||(g.zv(a.Na),b=Mrb({gm:0,gk:5,Po:5,qs:2,textAlign:0,Ii:0,lang:"en-GB"}),a.Sa=[b],c=["Click "," for settings"],a.rb||(e=new g.XE(g.Rxa()),g.N(a,e),a.rb=e.element),e=b.end-b.start,(f=g.fS(a.B))&&a.Sa.push(new y4(b.start,e,0,b.id,f)),a.Sa.push(new y4(b.start,e,0,b.id,c[0]),new y4(b.start,e,0,b.id,a.rb,
!0),new y4(b.start,e,0,b.id,c[1],!0)),a.player.gf(a.Sa),g.xv(a.Na));!a.Y||a.Fa||X4(a)||(g.QR(a.W)?Z4(a,!0):$4(a,!0),a.N&&(a.N.D=a.B),a.player.To());a.Y=!1}}),this.D||this.Fa||X4(this)||this.player.Cc("captionschanged",g.gS(this.B))):(this.j=ksb(this),g.N(this,this.j),this.j.OA(function(){msb(a)}))};
g.k.unload=function(){this.D&&this.B?nsb(this,!1):(this.Na&&g.zv(this.Na),this.player.nf("captions"),this.Ha=[],this.j&&this.j.Js(),this.eb.clear(),this.Z&&this.player.gf(this.Z),this.HT());g.tV.prototype.unload.call(this);this.player.To();this.player.Cc("captionschanged",{})};
g.k.create=function(){this.Qu()&&this.load();var a;a:{var b,c,d;if(this.W.L("web_player_nitrate_promo_tooltip")&&(null==(b=this.videoData.getPlayerResponse())?0:null==(c=b.captions)?0:null==(d=c.playerCaptionsTracklistRenderer)?0:d.enableTouchCaptionsNitrate)){var e,f;if(b=null==(a=this.videoData.getPlayerResponse())?void 0:null==(e=a.captions)?void 0:null==(f=e.playerCaptionsTracklistRenderer)?void 0:f.captionTracks)for(a=g.u(b),e=a.next();!e.done;e=a.next())if(e=e.value,"asr"===e.kind&&"en"===e.languageCode){a=
!0;break a}}a=!1}a&&this.J.publish("showpromotooltip",this.K.element)};
g.k.lca=function(){for(var a=this.J.Re().Ib().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=g.uV(this.j.B,!0);for(var d=0;d<b.length;d++)if(b[d].toString()===a[c].id){b=b[d];break a}b=null}(this.loaded?this.B:null)!==b&&Y4(this,b,!0)};
g.k.Fea=function(){!this.B&&this.D||this.unload()};
g.k.onCueRangeEnter=function(a){this.Ha.push(a);m4(this.La)};
g.k.onCueRangeExit=function(a){g.Hb(this.Ha,a);this.j instanceof o4&&this.j.K&&this.player.Lo([a]);m4(this.La)};
g.k.getCaptionWindowContainerId=function(){return this.K.element.id};
g.k.fda=function(){ssb(this,this.Sa);this.Sa=null};
g.k.ET=function(){var a=this;if(!this.Hb||!this.D){this.La.stop();g.eba(this.Va);this.Ha.sort(g.oCa);var b=this.Ha;if(this.Z){var c=g.Nt(b,function(f){return-1===this.Z.indexOf(f)},this);
c.length&&(b=c)}b=g.u(b);for(c=b.next();!c.done;c=b.next())qsb(this,c.value);b=g.u(Object.entries(this.ra));var d=b.next();for(c={};!d.done;c={rA:void 0,yp:void 0},d=b.next()){var e=g.u(d.value);d=e.next().value;e=e.next().value;c.rA=d;c.yp=e;this.Va[c.rA]?(c.yp.element.parentNode||(c.yp instanceof Q4||c.yp instanceof L4||g.Yc(this.ra,function(f){return function(h,l){l!==f.rA&&h.B.params.gm===f.yp.B.params.gm&&h.B.params.gk===f.yp.B.params.gk&&h.B.params.Po===f.yp.B.params.Po&&(h.dispose(),delete a.ra[l]);
return l===f.rA}}(c),this),this.K.element.appendChild(c.yp.element)),c.yp.cC(this.Va[c.rA])):(c.yp.dispose(),delete this.ra[c.rA])}}};
g.k.lda=function(){gsb(this,{},!0);this.player.Cc("captionssettingschanged")};
g.k.K8=function(){var a=a5.Pe;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:a5.windowColor,windowOpacity:a5.windowOpacity};var b=Zqb()||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&(a.backgroundOpacity=
b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&(a.fontSizeIncrement=
b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);null!=b.windowOpacity&&
(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.L2=function(a,b){var c={};Object.assign(c,Zqb());Object.assign(c,a);gsb(this,c,b);this.player.Cc("captionssettingschanged")};
g.k.HT=function(){!this.D&&this.loaded&&(g.Uc(this.ra,function(a,b){a.dispose();delete this.ra[b]},this),this.ET())};
g.k.Qh=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.ze(b,-2,4);this.L2({fontSizeIncrement:c});return c;case "reload":b&&!this.D&&Y4(this,this.B,!0);break;case "stickyLoading":void 0!==b&&this.W.N&&(g.QR(this.W)?Z4(this,!!b):$4(this,!!b));break;case "track":if(!this.j)return{};if(b){if(this.D)break;if(!g.db(b))break;if(g.gd(b)){Y4(this,null,!0);break}a=g.uV(this.j.B,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&(e.languageName!==b.languageName||
(e.captionId||"")!==(b.captionId||"")||g.fS(e)!==b.displayName)||(c=b.translationLanguage?Tqb(e,b.translationLanguage):e)}this.mM(b.position);!c||c===this.B&&this.loaded||(b=g.oPa(),a=g.hS(c),b.length&&a===b[b.length-1]||(b.push(a),g.PB("yt-player-caption-language-preferences",b)),g.QR(this.W)&&!this.J.isInline()&&g.PB("yt-player-caption-sticky-language",a,2592E3),Y4(this,c,!0))}else return this.loaded&&this.B&&!X4(this)?g.gS(this.B):{};return"";case "tracklist":return this.j?g.Zr(g.uV(this.j.B,!(!b||
!b.includeAsr)),function(f){return g.gS(f)}):[];
case "translationLanguages":return this.j?this.j.D.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.D||void 0===b||tsb(this,!!b);break;case "sampleSubtitlesCustomized":this.D||tsb(this,!!b,b);break;case "recommendedTranslationLanguages":return g.oPa();case "defaultTranslationSourceTrackIndices":return this.j?this.j.N:[]}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.W.N&&a.push("stickyLoading");return a};
g.k.Cr=function(){var a=this.B;if(this.W.L("html5_cue_ranges_based_caption_vss")&&!this.J.LJ("captions"))return{};if(this.W.L("html5_modify_caption_vss_logging")){var b;return(a=null!=(b=this.videoData.lD)?b:null)?{cc:g.bVa(a)}:{}}return a?(b=a.vssId,a.translationLanguage&&b&&(b="t"+b+"."+g.hS(a)),{cc:b}):{}};
g.k.qea=function(){this.isSubtitlesOn()?(g.QR(this.W)?Z4(this,!1):$4(this,!1),osb(this),this.unload(),U4(this,!0)&&Y4(this,V4(this),!1)):this.e2()};
g.k.e2=function(){this.isSubtitlesOn()||Y4(this,X4(this)||!this.B?W4(this,!0):this.B,!0)};
g.k.isSubtitlesOn=function(){return!!this.loaded&&!!this.B&&!X4(this)};
g.k.Y$=function(){var a=X4(this);U4(this,a)?Y4(this,this.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.bT()&&(this.Y=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null)),this.Qu()&&(a?Y4(this,W4(this),!1):this.load()))};
g.k.mM=function(a){a&&(this.qa={top:a.top,right:a.right,bottom:a.bottom,left:a.left,width:1-a.left-a.right,height:1-a.top-a.bottom},this.K.element.style.top=100*this.qa.top+"%",this.K.element.style.left=100*this.qa.left+"%",this.K.element.style.width=100*this.qa.width+"%",this.K.element.style.height=100*this.qa.height+"%",this.K.element.style.position="absolute",a=rsb(this))&&(this.K.element.style.width=a.width+"px",this.K.element.style.height=a.height+"px")};
g.k.onVideoDataChange=function(a,b){"newdata"===a&&(this.videoData=b,this.loaded&&this.unload(),this.Y=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null,this.player.Cc("captionschanged",{})),this.Qu()&&this.load())};
g.k.getAudioTrack=function(){return this.gb&&2===this.player.getPresentingPlayerType()?this.videoData.Jk:this.player.getAudioTrack()};
g.k.Maa=function(){var a=this.J.Re();a&&!a.Ma()&&a.zz();this.J.isFullscreen()?(this.D=this.Wa=!0,this.loaded&&msb(this)):(this.Wa="3"===this.W.controlsType,this.D=fsb(this));Y4(this,this.B)};
g.k.FM=function(){var a,b,c,d=null==(a=this.videoData.getPlayerResponse())?void 0:null==(b=a.captions)?void 0:null==(c=b.playerCaptionsTracklistRenderer)?void 0:c.openTranscriptCommand;d&&this.player.jb("innertubeCommand",d)};
g.LX.WJ(T4,{ET:"smucd"});g.sV("captions",T4);})(_yt_player);
