(function(g){var window=this;'use strict';var uwb=function(a,b){g.W.call(this,{I:"button",Ka:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],X:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},V:[{I:"svg",X:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},V:[{I:"g",X:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},V:[{I:"g",X:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
V:[{I:"path",X:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.J=a;this.listen("click",this.onClick,this);this.updateValue("title",g.LT(a,"Expand","i"));this.update({"data-title-no-tooltip":"Expand"});this.addOnDisposeCallback(g.JT(b.Se(),this.element))},vwb=function(a){g.W.call(this,
{I:"div",
S:"ytp-miniplayer-ui"});this.G=!1;this.player=a;this.T(a,"minimized",this.kh);this.T(a,"onStateChange",this.Wda)},wwb=function(a){g.tV.call(this,a);
this.B=new g.XJ(this);this.j=new vwb(this.player);this.j.hide();g.TT(this.player,this.j.element,4);a.isMinimized()&&(this.load(),g.Iv(a.getRootNode(),"ytp-player-minimized",!0))};
g.y(uwb,g.W);uwb.prototype.onClick=function(){this.J.jb("onExpandMiniplayer")};g.y(vwb,g.W);g.k=vwb.prototype;
g.k.show=function(){this.j=new g.vv(this.O4,null,this);this.j.start();if(!this.G){this.tooltip=new g.xX(this.player,this);g.N(this,this.tooltip);g.TT(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.je=new g.ZV(this.player);g.N(this,this.je);this.B=new g.W({I:"div",S:"ytp-miniplayer-scrim"});g.N(this,this.B);this.B.Ja(this.element);this.T(this.B.element,"click",this.L_);var a=new g.W({I:"button",Ka:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Close"},V:[g.hF()]});g.N(this,
a);a.Ja(this.B.element);this.T(a.element,"click",this.xU);a=new uwb(this.player,this);g.N(this,a);a.Ja(this.B.element);this.C=new g.W({I:"div",S:"ytp-miniplayer-controls"});g.N(this,this.C);this.C.Ja(this.B.element);this.T(this.C.element,"click",this.L_);var b=new g.W({I:"div",S:"ytp-miniplayer-button-container"});g.N(this,b);b.Ja(this.C.element);a=new g.W({I:"div",S:"ytp-miniplayer-play-button-container"});g.N(this,a);a.Ja(this.C.element);var c=new g.W({I:"div",S:"ytp-miniplayer-button-container"});
g.N(this,c);c.Ja(this.C.element);this.N=new g.LW(this.player,this,!1);g.N(this,this.N);this.N.Ja(b.element);b=new g.KW(this.player,this);g.N(this,b);b.Ja(a.element);this.nextButton=new g.LW(this.player,this,!0);g.N(this,this.nextButton);this.nextButton.Ja(c.element);this.K=new g.qX(this.player,this);g.N(this,this.K);this.K.Ja(this.B.element);this.progressBar=new g.QW(this.player,this);g.N(this,this.progressBar);g.TT(this.player,this.progressBar.element,4);this.D=new g.W({I:"div",S:"ytp-miniplayer-buttons"});
g.N(this,this.D);g.TT(this.player,this.D.element,4);a=new g.W({I:"button",Ka:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Close"},V:[g.hF()]});g.N(this,a);a.Ja(this.D.element);this.T(a.element,"click",this.xU);a=new g.W({I:"button",Ka:["ytp-miniplayer-replay-button","ytp-button"],X:{"aria-label":"Close"},V:[g.Qxa()]});g.N(this,a);a.Ja(this.D.element);this.T(a.element,"click",this.Bba);this.T(this.player,"presentingplayerstatechange",this.P4);this.T(this.player,"appresize",this.jc);
this.T(this.player,"fullscreentoggled",this.jc);this.jc();this.G=!0}0!==this.player.getPlayerState()&&g.W.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.k.hide=function(){this.j&&(this.j.dispose(),this.j=void 0);g.W.prototype.hide.call(this);this.player.isMinimized()||(this.G&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.k.va=function(){this.j&&(this.j.dispose(),this.j=void 0);g.W.prototype.va.call(this)};
g.k.xU=function(){this.player.stopVideo();this.player.jb("onCloseMiniplayer")};
g.k.Bba=function(){this.player.playVideo()};
g.k.L_=function(a){if(a.target===this.B.element||a.target===this.C.element)this.player.getPlayerStateObject().isOrWillBePlaying()?this.player.pauseVideo():this.player.playVideo()};
g.k.kh=function(){g.Iv(this.player.getRootNode(),"ytp-player-minimized",this.player.isMinimized())};
g.k.Bg=function(){this.progressBar.Sc();this.K.Sc()};
g.k.O4=function(){this.Bg();this.j&&this.j.start()};
g.k.P4=function(a){g.LF(a.state,32)&&this.tooltip.hide()};
g.k.jc=function(){g.k3a(this.progressBar,0,this.player.ob().getPlayerSize().width,!1);g.RW(this.progressBar)};
g.k.Wda=function(a){this.player.isMinimized()&&(0===a?this.hide():this.show())};
g.k.Se=function(){return this.tooltip};
g.k.Rx=function(a,b,c,d,e){var f=0,h=d=0,l=g.Ts(a);if(b){c=g.Dv(b,"ytp-prev-button")||g.Dv(b,"ytp-next-button");var m=g.Dv(b,"ytp-play-button"),n=g.Dv(b,"ytp-miniplayer-expand-watch-page-button");c?f=h=12:m?(b=g.Rs(b,this.element),h=b.x,f=b.y-12):n&&(h=g.Dv(b,"ytp-miniplayer-button-top-left"),f=g.Rs(b,this.element),b=g.Ts(b),h?(h=8,f=f.y+40):(h=f.x-l.width+b.width,f=f.y-20))}else h=c-l.width/2,d=25+(e||0);b=this.player.ob().getPlayerSize().width;e=f+(e||0);l=g.ze(h,0,b-l.width);e?(a.style.top=e+"px",
a.style.bottom=""):(a.style.top="",a.style.bottom=d+"px");a.style.left=l+"px"};g.y(wwb,g.tV);g.k=wwb.prototype;g.k.onVideoDataChange=function(){if(this.player.getVideoData()){var a=this.player.getVideoAspectRatio(),b=16/9;a=a>b+.1||a<b-.1;g.Iv(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",a)}};
g.k.create=function(){g.tV.prototype.create.call(this);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.k.Rm=function(){return!1};
g.k.load=function(){this.player.hideControls();this.j.show()};
g.k.unload=function(){this.player.showControls();this.j.hide()};g.sV("miniplayer",wwb);})(_yt_player);
